#!/bin/bash
#SBATCH -N 1
#SBATCH -n 4
#SBATCH -t 2:00:00
#SBATCH -J geos
#SBATCH -o frontier-%j-compflow-geom02.out

echo `date`
module load cpe/23.12
module load craype-accel-amd-gfx90a
module load rocm/5.4.3
export MPICH_GPU_SUPPORT_ENABLED=1
ldd ${1}
cmd="srun -N 1 -n 4 -c 1 --gpus-per-node=4 --ntasks-per-gpu=1 --gpu-bind=closest ${1} -i ECP_Wellbore_gpu.xml -x 1 -y 1 -z 4 ${2}"
echo "${cmd}"
${cmd}
echo `date`
echo 'Done'
