#!/bin/bash
#SBATCH -N 32
#SBATCH -n 256
#SBATCH -t 2:00:00
#SBATCH -J geos
#SBATCH -o frontier-%j-compflow-geom04.out

echo `date`
module load cpe/23.12
module load craype-accel-amd-gfx90a
module load rocm/5.4.3
export MPICH_GPU_SUPPORT_ENABLED=1
ldd ${1}
cmd="srun -N 32 -n 256 -c 1 --gpus-per-node=8 --ntasks-per-gpu=1 --gpu-bind=closest ${1} -i ECP_Wellbore_gpu.xml -x 4 -y 4 -z 16 ${2}"
echo "${cmd}"
${cmd}
echo `date`
echo 'Done'
