baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3233-6300-a0ac437

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
