baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3213-6170-5c2c0bf

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
