baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3100-5620-afd9708

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
