baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3138-5526-f053f0a

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
