baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3302-7220-387d58e

allow_fail:
  all: ''
  streak: SeismicityRate_poromechanics_1d_smoke_01,SeismicityRate_poromechanics_1d_smoke_02
