baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3135-6971-8b94b00

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
