---
baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3141-5289-995723a

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
