baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3120-5441-d1e1daf

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
