baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3194-6060-e5ba0ce

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
