---
baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3050-5125-d8a56bc

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
