baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3300-7077-1277f18

allow_fail:
  all: ''
  streak: SeismicityRate_poromechanics_1d_smoke_01,SeismicityRate_poromechanics_1d_smoke_02
