baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3196-5835-6563552.tar.gz

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
