baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3006-5860-947a907

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
