baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3283-6949-4ee437f

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
