baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3130-5671-b19ba86

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
