baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3088-5630-5ecff59

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
