---
baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr2917-4878-4907334

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
