baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3142-5705-ebdd3cb

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
