baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3215-6396-9b43cc8

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
