---
baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3060-4956-54ac336

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
