baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3021-5397-b33892f

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
