baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3021-5589-3c278fb

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
