baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3133-5610-b42c02a

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
