baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3165-5641-568d6e7

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
