baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3050-5325-9f50d94

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
