baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3213-6002-8736c9d

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
