baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3080-5511-8210a1a

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
