---
baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr2593-4950-bf205af

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
