---
baselines:
  bucket: geosx
  baseline: integratedTests/bbaseline_integratedTests-pr3125-5056-bf6930d

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
