baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3197-6679-a003f43

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
