baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3075-5458-8cde9da

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
