baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3140-5514-fe26f80

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
