baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3170-5687-d6e16c7

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
