---
baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3044-4865-1a337ae

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
