baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3080-5465-22c5b8b

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
