baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3250-6721-9473e59

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
