baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3249-6781-4998bc8

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
