baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3322-7333-3b1cff1

allow_fail:
  all: ''
  streak: SeismicityRate_poromechanics_1d_smoke_01,SeismicityRate_poromechanics_1d_smoke_02
