---
baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3120-4966-200edc3

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
