baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3302-7289-4ec7c0d

allow_fail:
  all: ''
  streak: SeismicityRate_poromechanics_1d_smoke_01,SeismicityRate_poromechanics_1d_smoke_02
