baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3152-5558-5c6e97f

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
