baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3278-6753-f7f9add

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
