baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3302-7280-41249ff

allow_fail:
  all: ''
  streak: SeismicityRate_poromechanics_1d_smoke_01,SeismicityRate_poromechanics_1d_smoke_02
