baselines:
  bucket: geosx
  baseline: integratedTests/baseline_integratedTests-pr3113-5435-b794227

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
