baselines:
  bucket: https://storage.googleapis.com/geosx/geosx
  baseline: integratedTests/baseline_integratedTests-pr3125-5101-7764ffb.tar.gz

allow_fail:
  all: ''
  streak: pennyShapedToughnessDominated_smoke_01,pennyShapedViscosityDominated_smoke_01,pknViscosityDominated_smoke_01
