# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-20.04
  tools:
    nodejs: 16
    python: 3.7
  jobs:
    post_system_dependencies:
    - npm install -g @mermaid-js/mermaid-cli

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
  - requirements: src/docs/sphinx/requirements.txt

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: src/conf.py
  builder: html

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

submodules:
  include: 
  - src/coreComponents/LvArray
  - integratedTests
  recursive: true
