# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: "ubuntu-20.04"
  apt_packages:
  - npm
  - plantuml
  tools:
    nodejs: "16"
    python: "3.7"
  jobs:
    post_install:
    - npm install -g npm
    - npm install -g @mermaid-js/mermaid-cli

# Set requirements to build the docs
python:
  install:
  - requirements: src/docs/sphinx/requirements.txt

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: src/conf.py
  builder: html

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

submodules:
  include: 
  - src/coreComponents/LvArray
  - src/coreComponents/constitutive/PVTPackage
  - integratedTests
  recursive: true
