name: macos

on:
  pull_request:
    branches: [ main ]

jobs:
  # Test uberenv-pkg Spack build mode in macos
  build_uberenv_mode:
    name: Uberenv Build Mode (MacOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Uberenv
        run: |
          cd  .ci/test-project
          python3 ../../uberenv.py --project-json=uberenv_configs/uberenv-pkg.json
          cat uberenv_libs/*.cmake
