#!/usr/bin/env python3
"""Compatibility entry point for older documentation workflows.

Narrative LaTeX source is no longer generated by Python.  This wrapper refreshes
only generated/data when requested and always refreshes generated/tex.  Use
./build_manual.sh to refresh generated tables and compile the PDF.
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path


def find_repo_root(doc_dir: Path) -> Path:
    env_root = os.environ.get("GEOS_REPO_ROOT")
    if env_root:
        return Path(env_root).resolve()
    try:
        root = subprocess.check_output(
            ["git", "-C", str(doc_dir), "rev-parse", "--show-toplevel"],
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
        if root:
            return Path(root).resolve()
    except Exception:
        pass
    candidate = (doc_dir / "../../../..").resolve()
    if (candidate / "src").is_dir() and (candidate / "scripts").is_dir():
        return candidate
    raise SystemExit("Could not determine GEOS repository root. Set GEOS_REPO_ROOT=/path/to/geos.")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--refresh-data", action="store_true", help="re-extract generated/data from the current source checkout")
    args = parser.parse_args()

    doc_dir = Path(__file__).resolve().parent
    data_json = doc_dir / "generated" / "data" / "geos_mpm_extracted.json"
    generated_tex = doc_dir / "generated" / "tex"
    data_json.parent.mkdir(parents=True, exist_ok=True)
    generated_tex.mkdir(parents=True, exist_ok=True)

    if args.refresh_data or not data_json.exists():
        repo_root = find_repo_root(doc_dir)
        subprocess.run(
            [sys.executable, str(doc_dir / "tools" / "extract_mpm_metadata.py"), "--repo", str(repo_root), "--out", str(data_json)],
            check=True,
        )
    subprocess.run(
        [sys.executable, str(doc_dir / "tools" / "render_generated_tex.py"), "--in", str(data_json), "--out", str(generated_tex)],
        check=True,
    )
    print("Refreshed generated/tex. Narrative files under tex/ were not modified.")


if __name__ == "__main__":
    main()
