#ifndef GEOS_LINEARALGEBRA_INTERFACES_HYPRE_HYPREDRIVE_HPP_
#define GEOS_LINEARALGEBRA_INTERFACES_HYPRE_HYPREDRIVE_HPP_

#include "common/LinearSolverBase.hpp"
#include "linearAlgebra/interfaces/hypre/HypreInterface.hpp"

#include <HYPREDRV.h>

#include <memory>
#include <string>

namespace geos
{

class HypreSolver;
class HypredriveSolverTestPeer;

namespace hypre
{

namespace hypredrive
{

/**
 * @brief Source used to populate `HYPREDRV_InputArgsParse`.
 */
enum class InputSource
{
  /// Use the user-provided authoritative hypredrive input file.
  authoritativeFile,
  /// Use YAML generated by GEOS as a fallback configuration.
  generatedFallback
};

/**
 * @brief Parsed-input payload passed to `HYPREDRV_InputArgsParse`.
 */
struct InputArgsParseTarget
{
  /// Origin of the payload stored in `argument`.
  InputSource source = InputSource::generatedFallback;
  /// File path or YAML string consumed by `HYPREDRV_InputArgsParse`.
  std::string argument;
};

bool shouldUse( LinearSolverParameters const & params );

bool buildInputArgsParseTarget( LinearSolverParameters const & params,
                                InputArgsParseTarget & target );

bool buildInputArgsParseTarget( LinearSolverParameters const & params,
                                stdVector< string > const & fieldNames,
                                arrayView1d< int const > const & numComponentsPerField,
                                InputArgsParseTarget & target );

std::string formatInputArgsParseTargetYaml( InputArgsParseTarget const & target );

bool wasInputArgsParseTargetLogged( InputArgsParseTarget const & target );

void markInputArgsParseTargetLogged( InputArgsParseTarget const & target );

void logInputArgsParseTarget( LinearSolverParameters const & params,
                              InputArgsParseTarget const & target );

void initializeRuntime();

void finalizeRuntime();

}

}

/**
 * @brief Linear solver adapter that routes GEOS Hypre systems through hypredrive.
 *
 * The solver owns a `HYPREDRV_t` handle when hypredrive is active and falls back
 * to the legacy Hypre solver path when the requested configuration is unsupported.
 */
class HypredriveSolver final : public LinearSolverBase< HypreInterface >
{
public:

  /// Alias for the common linear-solver base implementation.
  using Base = LinearSolverBase< HypreInterface >;

  /**
   * @brief Construct a hypredrive-backed linear solver.
   * @param parameters GEOS linear-solver parameters used to configure hypredrive.
   */
  explicit HypredriveSolver( LinearSolverParameters parameters );

  /// Destroys the managed hypredrive object and releases any fallback solver state.
  ~HypredriveSolver() override;

  /**
   * @brief Update the execution metadata associated with subsequent solves.
   * @param context Current solve context from the owning physics solver.
   */
  void setExecutionContext( LinearSolverExecutionContext const & context ) override;

  /**
   * @brief Set near-null-space modes to pass to HypreDrive during setup.
   * @param nearNullKernel Full-system distributed near-null-space vectors.
   */
  void setNearNullKernel( arrayView1d< HypreVector const > const & nearNullKernel ) override;

  /**
   * @brief Build or refresh the solver/preconditioner for a matrix.
   * @param mat Matrix that defines the system structure and coefficients.
   */
  void setup( HypreMatrix const & mat ) override;

  /**
   * @brief Apply the configured operator as a preconditioner action.
   * @param src Input vector.
   * @param dst Output vector receiving the operator application.
   */
  void apply( HypreVector const & src,
              HypreVector & dst ) const override;

  /**
   * @brief Solve the linear system with hypredrive.
   * @param rhs Right-hand side vector.
   * @param sol Input initial guess and output solution vector.
   */
  void solve( HypreVector const & rhs,
              HypreVector & sol ) const override;

  /// Reset solver-owned state and destroy any active hypredrive object.
  void clear() override;

private:

  bool configureHypredrive( HypreMatrix const & mat );

  void createHypredrive( HypreMatrix const & mat,
                         hypre::hypredrive::InputArgsParseTarget const & parseTarget,
                         std::string const & configurationSignature,
                         std::string const & structureSignature,
                         arrayView1d< int > const & pointMarkers );

  void refreshBoundObjects( HypreMatrix const & mat,
                            arrayView1d< int > const & pointMarkers );

  void setupLegacy( HypreMatrix const & mat );

  void applyHypredrive( HypreVector const & rhs,
                        HypreVector & sol ) const;

  void syncExecutionAnnotations();

  void closeExecutionAnnotations();

  void syncLegacyResult() const;

  void destroyHypredrive();

  void resetHypredriveState();

  using Base::m_params;
  using Base::m_result;

  friend class HypredriveSolverTestPeer;

  LinearSolverExecutionContext m_executionContext{};
  std::string m_configurationSignature;
  std::string m_structureSignature;
  std::string m_activeTimestepScope;
  std::string m_activeNewtonScope;
  bool m_hasExecutionContext = false;
  bool m_timestepScopeActive = false;
  bool m_newtonScopeActive = false;
  arrayView1d< HypreVector const > m_nearNullKernel;
  bool m_reportedGeneratedYamlFailure = false;
  size_t m_hypredriveGeneration = 0;
  HYPREDRV_t m_hypredrive{};
  bool m_linearSolverCreated = false;
  mutable HypreVector m_dummyRhs;
  mutable HypreVector m_dummySol;
  mutable HypreVector m_residual;
  std::unique_ptr< HypreSolver > m_legacySolver;
};

}

#endif
