#!/usr/bin/env python3
"""Aggregate post-processing for the MMS vortex verification folder.

This script is intentionally folder-scoped.  It reads the two variant run
directories generated by runTest, reduces their tracer CSV files to the same
quantitative displacement metric, renders the requested VisIt images when VisIt
is available, and writes the plots/tables used by test.tex.
"""
from __future__ import annotations

import argparse
import csv
import json
import math
import os
import shutil
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

AMPLITUDE = 1.0
INNER_RADIUS = 0.75
OUTER_RADIUS = 1.25
PERIOD = 1.0
TRACER_PREFIX = "mmsVortexTracer"

VARIANTS = [
    {
        "name": "cpdiFlip",
        "label": "CPDI-FLIP",
        "case_name": "mmsVortex_cpdiFlip",
    },
    {
        "name": "fmpmSinglePointBspline",
        "label": "FMPM/singlePointBspline",
        "case_name": "mmsVortex_fmpmSinglePointBspline",
    },
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Post-process all MMS vortex variants")
    parser.add_argument("--suite", default="verification")
    parser.add_argument("--source-dir", required=True)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--case-id", default="mmsVortex")
    parser.add_argument("--python", dest="python_cmd", default=sys.executable)
    parser.add_argument("--visit-cmd", default=os.environ.get("VISIT_COMMAND", ""))
    parser.add_argument("--no-visit", action="store_true")
    parser.add_argument("--force", action="store_true")
    return parser.parse_args()


def compact_float(value: float) -> str:
    return f"{float(value):.10g}"


def latex_escape(value: object) -> str:
    text = str(value if value is not None else "")
    repl = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_", "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}
    return "".join(repl.get(ch, ch) for ch in text)


def variant_case_id(folder_case_id: str, variant: dict[str, str]) -> str:
    return f"{folder_case_id}__{variant['name']}"


def load_manifest(source_dir: Path, output_dir: Path, case_id: str) -> dict:
    manifest_path = output_dir / "mmsVortex_jobs.json"
    if manifest_path.is_file():
        try:
            return json.loads(manifest_path.read_text())
        except Exception:
            pass
    subcases = []
    for variant in VARIANTS:
        cid = variant_case_id(case_id, variant)
        jobs_path = source_dir / "output" / cid / f"{variant['case_name']}_jobs.json"
        jobs = {}
        if jobs_path.is_file():
            try:
                jobs = json.loads(jobs_path.read_text())
            except Exception:
                jobs = {}
        subcases.append({"name": variant["name"], "label": variant["label"], "case_id": cid, "case_name": variant["case_name"], "jobs": jobs})
    return {"case_id": case_id, "subcases": subcases}


def tracer_files(run_dir: Path) -> list[Path]:
    patterns = [f"{TRACER_PREFIX}_*.csv", "tracerPoint_*.csv"]
    out: list[Path] = []
    for pattern in patterns:
        out.extend(sorted(run_dir.glob(pattern)))
    return sorted(set(out))


def read_tracer(path: Path) -> list[dict[str, float]]:
    rows: list[dict[str, float]] = []
    with path.open(newline="") as handle:
        reader = csv.DictReader(handle)
        required = {"t", "x", "y", "z"}
        missing = required - set(reader.fieldnames or [])
        if missing:
            raise ValueError(f"{path.name} is missing columns: {sorted(missing)}")
        for row in reader:
            rows.append({key: float(value) for key, value in row.items() if value not in (None, "")})
    if len(rows) < 2:
        raise ValueError(f"{path.name} has too few tracer samples")
    return rows


def vortex_alpha(radius: float, time: float) -> float:
    if not (INNER_RADIUS < radius < OUTER_RADIUS):
        return 0.0
    r_offset = radius - 1.0
    spatial = 1.0 - 32.0 * r_offset * r_offset + 256.0 * r_offset**4
    temporal = 1.0 - math.cos(2.0 * math.pi * time / PERIOD)
    return 0.5 * AMPLITUDE * temporal * spatial


def analytic_displacement_norm(x0: float, y0: float, time: float) -> float:
    radius = math.hypot(x0, y0)
    alpha = vortex_alpha(radius, time)
    return 2.0 * radius * abs(math.sin(0.5 * alpha))


def collect_metrics(run_dir: Path) -> tuple[list[dict[str, float]], dict[str, float]]:
    files = tracer_files(run_dir)
    if not files:
        raise FileNotFoundError(f"No tracer CSV files matching {TRACER_PREFIX}_*.csv in {run_dir}")

    buckets: dict[float, list[tuple[float, float, float]]] = defaultdict(list)
    for path in files:
        rows = read_tracer(path)
        x0 = rows[0]["x"]
        y0 = rows[0]["y"]
        z0 = rows[0]["z"]
        for row in rows:
            time = row["t"]
            dx = row["x"] - x0
            dy = row["y"] - y0
            dz = row["z"] - z0
            measured = math.sqrt(dx * dx + dy * dy + dz * dz)
            exact = analytic_displacement_norm(x0, y0, time)
            buckets[round(time, 12)].append((measured, exact, measured - exact))

    history: list[dict[str, float]] = []
    for time in sorted(buckets):
        values = buckets[time]
        n = float(len(values))
        mean_measured = sum(v[0] for v in values) / n
        mean_exact = sum(v[1] for v in values) / n
        mean_abs_error = sum(abs(v[2]) for v in values) / n
        rms_error = math.sqrt(sum(v[2] * v[2] for v in values) / n)
        max_abs_error = max(abs(v[2]) for v in values)
        history.append(
            {
                "time": time,
                "num_tracers": len(values),
                "mean_displacement_norm": mean_measured,
                "mean_exact_displacement_norm": mean_exact,
                "mean_abs_error": mean_abs_error,
                "rms_error": rms_error,
                "max_abs_error": max_abs_error,
            }
        )

    final = history[-1]
    peak = max(history, key=lambda row: row["mean_exact_displacement_norm"])
    summary = {
        "num_tracer_files": len(files),
        "num_times": len(history),
        "final_time": final["time"],
        "final_mean_displacement_norm": final["mean_displacement_norm"],
        "final_mean_exact_displacement_norm": final["mean_exact_displacement_norm"],
        "final_rms_error": final["rms_error"],
        "peak_time": peak["time"],
        "peak_mean_displacement_norm": peak["mean_displacement_norm"],
        "peak_mean_exact_displacement_norm": peak["mean_exact_displacement_norm"],
        "peak_rms_error": peak["rms_error"],
        "peak_relative_rms_error": peak["rms_error"] / max(peak["mean_exact_displacement_norm"], 1.0e-30),
    }
    return history, summary


def write_variant_metrics(output_dir: Path, name: str, history: list[dict[str, float]], summary: dict[str, float]) -> None:
    fieldnames = [
        "time",
        "num_tracers",
        "mean_displacement_norm",
        "mean_exact_displacement_norm",
        "mean_abs_error",
        "rms_error",
        "max_abs_error",
    ]
    csv_path = output_dir / f"mms_vortex_{name}_tracer_metrics.csv"
    with csv_path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(history)
    (output_dir / f"mms_vortex_{name}_metric_summary.json").write_text(json.dumps(summary, indent=2, sort_keys=True))


def write_combined_csv(output_dir: Path, results: list[dict]) -> None:
    fieldnames = [
        "variant",
        "label",
        "time",
        "num_tracers",
        "mean_displacement_norm",
        "mean_exact_displacement_norm",
        "mean_abs_error",
        "rms_error",
        "max_abs_error",
    ]
    with (output_dir / "mms_vortex_tracer_metrics.csv").open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for result in results:
            for row in result.get("history", []):
                out = {"variant": result["name"], "label": result["label"]}
                out.update(row)
                writer.writerow(out)


def make_plots(output_dir: Path, results: list[dict]) -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    fig, ax = plt.subplots(figsize=(6.8, 4.4))
    for result in results:
        history = result.get("history", [])
        if not history:
            continue
        times = [row["time"] for row in history]
        measured = [row["mean_displacement_norm"] for row in history]
        exact = [row["mean_exact_displacement_norm"] for row in history]
        ax.plot(times, measured, label=result["label"])
        ax.plot(times, exact, "--", label=result["label"] + " analytical")
    ax.set_xlabel("time")
    ax.set_ylabel("average displacement norm")
    ax.grid(True, alpha=0.3)
    ax.legend(loc="best")
    fig.tight_layout()
    fig.savefig(output_dir / "mms_vortex_mean_displacement.png", dpi=180)
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(6.8, 4.4))
    for result in results:
        history = result.get("history", [])
        if not history:
            continue
        times = [row["time"] for row in history]
        rms = [row["rms_error"] for row in history]
        ax.plot(times, rms, label=result["label"])
    ax.set_xlabel("time")
    ax.set_ylabel("RMS displacement-norm error")
    ax.grid(True, alpha=0.3)
    ax.legend(loc="best")
    fig.tight_layout()
    fig.savefig(output_dir / "mms_vortex_displacement_error.png", dpi=180)
    plt.close(fig)


def detect_visit(requested: str) -> str | None:
    for candidate in [requested, os.environ.get("VISIT_CMD", ""), os.environ.get("VISIT_COMMAND", ""), "/usr/gapps/visit/bin/visit", "visit"]:
        if not candidate:
            continue
        if os.path.isabs(candidate) and os.access(candidate, os.X_OK):
            return candidate
        found = shutil.which(candidate)
        if found:
            return found
    return None


def run_visit(args: argparse.Namespace, run_dir: Path, output_dir: Path, result: dict) -> None:
    if args.no_visit:
        return
    visit = detect_visit(args.visit_cmd)
    renderer = run_dir / "pfw_visit_render.py"
    if not visit or not renderer.is_file():
        (output_dir / f"mms_vortex_{result['name']}_visit_skipped.txt").write_text("VisIt or pfw_visit_render.py was not available.\n")
        return
    image_dir = output_dir / "visit_frames" / result["name"]
    image_dir.mkdir(parents=True, exist_ok=True)
    log_path = output_dir / f"mms_vortex_{result['name']}_visit_render.log"
    commands = [
        ["--variable", "particleDisplacementMagnitude", "--mesh", "CellRegion1", "--range-mode", "auto"],
        ["--variable", "gridDisplacementMagnitude", "--mesh", "CellRegion1", "--range-mode", "auto"],
    ]
    with log_path.open("w") as log:
        for extra in commands:
            cmd = [
                visit,
                "-nowin",
                "-cli",
                "-s",
                str(renderer),
                "--run-dir",
                str(run_dir),
                "--output-dir",
                str(image_dir),
                "--case-name",
                result["case_name"],
                "--states",
                "initial,middle,final",
                "--view",
                "xy",
                "--list-databases",
            ] + extra
            log.write("Running: " + " ".join(cmd) + "\n")
            proc = subprocess.run(cmd, cwd=run_dir, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
            log.write(proc.stdout + f"\nreturncode={proc.returncode}\n")
            if proc.returncode != 0:
                log.write("WARNING: VisIt render failed; continuing.\n")


def write_tex(output_dir: Path, results: list[dict], warnings: list[str]) -> None:
    rows = []
    for result in results:
        summary = result.get("summary") or {}
        if not summary:
            rows.append(" & ".join([latex_escape(result.get("label", result.get("name", ""))), "missing", "--", "--", "--", latex_escape(result.get("warning", "no metrics"))]) + r" \\")
            continue
        rows.append(
            " & ".join(
                [
                    latex_escape(result["label"]),
                    compact_float(summary["peak_time"]),
                    compact_float(summary["peak_mean_displacement_norm"]),
                    compact_float(summary["peak_mean_exact_displacement_norm"]),
                    compact_float(summary["peak_relative_rms_error"]),
                    compact_float(summary["final_rms_error"]),
                ]
            )
            + r" \\")

    tex = r"""
\paragraph{Quantitative metric.}
The tracer metric is the mean norm of the lagrangian tracer displacement.  The
same annular tracer array is used for both numerical variants.  The analytical
comparison uses the generalized-vortex manufactured displacement evaluated at
the initial tracer locations.

\begin{center}
{\small
\begin{tabular}{l r r r r r}
\toprule
Variant & Peak time & Peak computed mean & Peak analytical mean & Peak rel. RMS error & Final RMS error \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
}
\end{center}

\begin{figure}[h!]
  \centering
  \includegraphics[width=0.47\linewidth]{\CaseOutputDir/mms_vortex_mean_displacement.png}
  \includegraphics[width=0.47\linewidth]{\CaseOutputDir/mms_vortex_displacement_error.png}
  \caption{MMS-vortex tracer displacement metric and error history for the CPDI-FLIP and FMPM/singlePointBspline variants.}
\end{figure}
"""
    frame_lines = []
    for result in results:
        frame_dir = output_dir / "visit_frames" / result["name"]
        if not frame_dir.is_dir():
            continue
        for frame in sorted(frame_dir.glob("*.png")):
            frame_lines.append((result["label"], result["name"], frame.name))
    if frame_lines:
        tex += "\n\\begin{figure}[h!]\n  \\centering\n"
        for _label, name, frame in frame_lines[:12]:
            tex += f"  \\includegraphics[width=0.31\\linewidth]{{\\CaseOutputDir/visit_frames/{name}/{frame}}}\n"
        tex += "  \\caption{Particle-displacement and background-grid MMS-vortex images at $t=0$, $t=t_{stop}/2$, and $t=t_{stop}$ for both variants.}\n\\end{figure}\n"
    else:
        tex += "\n\\paragraph{VisIt images.} Particle-displacement and background-grid images were not generated in this post-processing run.\n"
    if warnings:
        tex += "\n\\paragraph{Post-processing warnings.}\n\\begin{itemize}\n"
        for warning in warnings:
            tex += "  \\item " + latex_escape(warning) + "\n"
        tex += "\\end{itemize}\n"
    (output_dir / "mms_vortex_results.tex").write_text(tex.strip() + "\n")


def main() -> int:
    args = parse_args()
    source_dir = Path(args.source_dir).resolve()
    output_dir = Path(args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    manifest = load_manifest(source_dir, output_dir, args.case_id)
    results: list[dict] = []
    warnings: list[str] = []

    for variant in VARIANTS:
        existing = next((s for s in manifest.get("subcases", []) if s.get("name") == variant["name"]), {})
        jobs = existing.get("jobs", {}) or {}
        run_dir = Path(jobs.get("run_dir", "")) if jobs.get("run_dir") else None
        result = {
            "name": variant["name"],
            "label": variant["label"],
            "case_id": existing.get("case_id", variant_case_id(args.case_id, variant)),
            "case_name": variant["case_name"],
            "run_dir": str(run_dir) if run_dir else "",
        }
        if not run_dir or not run_dir.is_dir():
            warning = f"{variant['label']}: run directory was not found"
            result["warning"] = warning
            warnings.append(warning)
            results.append(result)
            continue
        try:
            history, summary = collect_metrics(run_dir)
            result["history"] = history
            result["summary"] = summary
            write_variant_metrics(output_dir, variant["name"], history, summary)
            run_visit(args, run_dir, output_dir, result)
        except Exception as exc:
            warning = f"{variant['label']}: {exc}"
            result["warning"] = warning
            warnings.append(warning)
        results.append(result)

    good_results = [result for result in results if result.get("history")]
    if good_results:
        write_combined_csv(output_dir, good_results)
        make_plots(output_dir, good_results)
    else:
        # Keep report generation robust even when GEOS failed before tracer output.
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        for name, title in [("mms_vortex_mean_displacement.png", "missing tracer metrics"), ("mms_vortex_displacement_error.png", "missing tracer metrics")]:
            fig, ax = plt.subplots(figsize=(6.8, 4.4))
            ax.text(0.5, 0.5, title, ha="center", va="center")
            ax.set_axis_off()
            fig.tight_layout()
            fig.savefig(output_dir / name, dpi=180)
            plt.close(fig)
    summary = {"case_id": args.case_id, "variants": [{k: v for k, v in result.items() if k not in {"history"}} for result in results], "warnings": warnings}
    (output_dir / "mms_vortex_metric_summary.json").write_text(json.dumps(summary, indent=2, sort_keys=True))
    write_tex(output_dir, results, warnings)
    print(json.dumps(summary, indent=2, sort_keys=True))
    return 0 if good_results and not warnings else 1


if __name__ == "__main__":
    raise SystemExit(main())
