site_name(HOST_NAME)

set(CMAKE_C_COMPILER "$ENV{CC}" CACHE PATH "" FORCE)
set(CMAKE_CXX_COMPILER "$ENV{CXX}" CACHE PATH "" FORCE)
set(ENABLE_FORTRAN OFF CACHE BOOL "" FORCE)

set(ENABLE_MPI ON CACHE PATH "" FORCE)
set(MPI_C_COMPILER "$ENV{MPICC}" CACHE PATH "" FORCE)
set(MPI_CXX_COMPILER "$ENV{MPICXX}" CACHE PATH "" FORCE)

set(MPIEXEC_EXECUTABLE "$ENV{MPIEXEC}" CACHE PATH "" FORCE)

set(ENABLE_GTEST_DEATH_TESTS ON CACHE BOOL "" FORCE)
set(ENABLE_CALIPER ON CACHE BOOL "")

set(ENABLE_GEOSX_PTP ON CACHE BOOL "" FORCE)

set(ENABLE_HYPRE "$ENV{ENABLE_HYPRE}" CACHE BOOL "" FORCE)
if(NOT ENABLE_HYPRE)
  set(ENABLE_HYPRE ON CACHE BOOL "" FORCE)
endif()

if(ENABLE_HYPRE)
  set(GEOSX_LA_INTERFACE "Hypre" CACHE STRING "" FORCE)
else()
  set(GEOSX_LA_INTERFACE "Trilinos" CACHE STRING "" FORCE)
endif()

set(ENABLE_TRILINOS "$ENV{ENABLE_TRILINOS}" CACHE BOOL "" FORCE)
if(NOT ENABLE_TRILINOS)
  set(ENABLE_TRILINOS ON CACHE BOOL "" FORCE)
endif()

set(ENABLE_CUDA "$ENV{ENABLE_CUDA}" CACHE BOOL "" FORCE)
if(ENABLE_CUDA)

  set(CMAKE_CUDA_FLAGS "$ENV{CMAKE_CUDA_FLAGS}" CACHE STRING "" FORCE)
  if(NOT CMAKE_CUDA_FLAGS)
    set(CMAKE_CUDA_FLAGS "Unused" CACHE STRING "" FORCE)
  endif()

  set(CUDA_TOOLKIT_ROOT_DIR "$ENV{CUDA_TOOLKIT_ROOT_DIR}" CACHE PATH "" FORCE)
  if(NOT CUDA_TOOLKIT_ROOT_DIR)
    set(CUDA_TOOLKIT_ROOT_DIR "/usr/local/cuda" CACHE PATH "" FORCE)
  endif()

  set(CUDA_ARCH "$ENV{CUDA_ARCH}" CACHE STRING "" FORCE)
  if(NOT CUDA_ARCH)
    set(CUDA_ARCH "sm_70" CACHE STRING "" FORCE)
  endif()

  set(ENABLE_HYPRE_CUDA "$ENV{ENABLE_HYPRE_CUDA}" CACHE BOOL "" FORCE)
  if(NOT ENABLE_HYPRE_CUDA)
    set(ENABLE_HYPRE_CUDA OFF CACHE BOOL "" FORCE)
  endif()

endif()

set(GEOSX_TPL_DIR "$ENV{GEOSX_TPL_DIR}" CACHE PATH "" FORCE)
include(${CMAKE_CURRENT_LIST_DIR}/tpls.cmake)
