site_name(HOST_NAME)

set(CMAKE_C_COMPILER "/usr/bin/gcc" CACHE PATH "" FORCE)
set(CMAKE_CXX_COMPILER "/usr/bin/g++" CACHE PATH "" FORCE)
set(ENABLE_FORTRAN OFF CACHE BOOL "" FORCE)

set(ENABLE_MPI ON CACHE PATH "" FORCE)
set(MPI_C_COMPILER "/usr/bin/mpicc" CACHE PATH "" FORCE)
set(MPI_CXX_COMPILER "/usr/bin/mpic++" CACHE PATH "" FORCE)

set(MPIEXEC_EXECUTABLE "/usr/bin/mpiexec" CACHE PATH "" FORCE)
set(ENABLE_GTEST_DEATH_TESTS ON CACHE BOOL "" FORCE )
