#!/usr/bin/env python3
"""Render source/schema-derived LaTeX snippets for the GEOS-MPM manual.

This script writes only to the generated LaTeX directory passed with --out.
Human-maintained narrative files under tex/ are intentionally not touched.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import textwrap
from pathlib import Path
from typing import Any

AUTO_HEADER = "% AUTO-GENERATED FILE. DO NOT EDIT.\n% Generated by tools/render_generated_tex.py.\n"


def ascii_clean(s: Any) -> str:
    if s is None:
        return ""
    s = str(s)
    s = s.replace("\u2013", "-").replace("\u2014", "--").replace("\u2212", "-")
    s = s.replace("\u2018", "'").replace("\u2019", "'").replace("\u201c", '"').replace("\u201d", '"')
    s = s.replace("\u00a0", " ")
    s = s.encode("ascii", "ignore").decode("ascii")
    return re.sub(r"\s+", " ", s).strip()


def tex(s: Any) -> str:
    s = ascii_clean(s)
    repl = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    out = "".join(repl.get(ch, ch) for ch in s)
    out = out.replace("<", r"\textless{}")
    out = out.replace(">", r"\textgreater{}")
    return out


def code(s: Any) -> str:
    """Escape a code token and allow safe line breaks."""
    out = tex(s)
    out = re.sub(r"([a-z0-9])([A-Z])", r"\1\\allowbreak{}\2", out)
    for token in [r"\_", "/", ".", "-", ","]:
        out = out.replace(token, token + r"\allowbreak{}")
    return r"{\ttfamily " + out + "}"


def path(s: Any) -> str:
    """Typeset a path-like string with discretionary breaks."""
    raw = ascii_clean(s)
    out = tex(raw)
    for token in ["/", r"\_", ".", "-"]:
        out = out.replace(token, token + r"\allowbreak{}")
    return r"{\ttfamily\footnotesize " + out + "}"


def tiny_path(s: Any) -> str:
    """Typeset a path-like string for very narrow generated tables."""
    return path(s).replace(r"\footnotesize", r"\tiny")


def longtable(
    headers: list[str],
    rows: list[list[str]],
    widths: list[str] | None = None,
    caption: str | None = None,
    label: str | None = None,
    size: str = r"\scriptsize",
) -> str:
    assert all(len(r) == len(headers) for r in rows)
    n = len(headers)
    if widths is None:
        widths = [f"p{{{0.95 / n:.2f}\\linewidth}}" for _ in range(n)]
    spec = "@{}" + "".join(widths) + "@{}"
    lines: list[str] = []
    lines.append(r"{\renewcommand{\arraystretch}{1.15}")
    lines.append(size)
    lines.append(r"\begin{longtable}{" + spec + "}")
    if caption:
        cap = r"\caption{" + tex(caption) + "}"
        if label:
            cap += r"\label{" + label + "}"
        cap += r"\\"
        lines.append(cap)
    lines.append(r"\toprule")
    lines.append(" & ".join(r"\textbf{" + tex(h) + "}" for h in headers) + r"\\")
    lines.append(r"\midrule")
    lines.append(r"\endfirsthead")
    lines.append(r"\toprule")
    lines.append(" & ".join(r"\textbf{" + tex(h) + "}" for h in headers) + r"\\")
    lines.append(r"\midrule")
    lines.append(r"\endhead")
    lines.append(r"\midrule")
    lines.append(r"\multicolumn{" + str(n) + r"}{r}{Continued on next page}\\")
    lines.append(r"\endfoot")
    lines.append(r"\bottomrule")
    lines.append(r"\endlastfoot")
    for row in rows:
        lines.append(" & ".join(row) + r"\\")
    lines.append(r"\end{longtable}")
    lines.append(r"}")
    return "\n".join(lines) + "\n"


def bullet_table(items: list[tuple[str, str]], caption: str, label: str | None = None) -> str:
    rows = [[r"\textbf{" + tex(a) + "}", tex(b)] for a, b in items]
    return longtable(["Topic", "Notes"], rows, [r"p{0.27\linewidth}", r"p{0.67\linewidth}"], caption, label, size=r"\small")


def format_default(value: Any, maxlen: int = 55) -> str:
    s = ascii_clean(value)
    if len(s) > maxlen:
        s = s[: maxlen - 3] + "..."
    if s == "":
        s = "-"
    return code(s)


def unique_by_name(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    seen: set[str] = set()
    out: list[dict[str, Any]] = []
    for r in rows:
        name = r.get("name") or ""
        if name in seen:
            continue
        seen.add(name)
        out.append(r)
    return out


def safe_write(out_dir: Path, name: str, body: str) -> None:
    out_dir = out_dir.resolve()
    path_out = (out_dir / name).resolve()
    if path_out != out_dir and out_dir not in path_out.parents:
        raise RuntimeError(f"Refusing to write outside generated directory: {path_out}")
    path_out.parent.mkdir(parents=True, exist_ok=True)
    path_out.write_text(AUTO_HEADER + textwrap.dedent(body).lstrip(), encoding="utf-8")


def render(data: dict[str, Any], out_dir: Path) -> None:
    # Source-count table used by the editable preface.
    source_counts = {
        "Solver attributes": len(data.get("solver_wrappers", [])),
        "MPM event types": len(data.get("event_data", [])),
        "PFW parameters": len(data.get("pfw_params", [])),
        "Particle file fields": len(data.get("particle_columns", [])),
        "Geometry objects": len(data.get("geometry_objects", [])),
        "Geometry wrappers": len(data.get("geometry_wrappers", [])),
        "Post-processing scripts": len(data.get("post_scripts", [])),
    }
    safe_write(
        out_dir,
        "source_counts_table.tex",
        bullet_table([(k, str(v)) for k, v in source_counts.items()], "Code-derived content counts in this starter manual.", "tab:source-counts"),
    )

    # Source inventory table.
    source_rows = [[tex(r["component"]), path(r["path"])] for r in data.get("source_inventory", [])]
    safe_write(
        out_dir,
        "source_inventory.tex",
        longtable(["Component", "Path"], source_rows, [r"p{0.30\linewidth}", r"p{0.63\linewidth}"], "Primary source files and directories used to generate this manual.", "tab:source-inventory", size=r"\small"),
    )

    # Solver attributes and enums.
    user_wrappers = [r for r in data.get("solver_wrappers", []) if r.get("flag") != "FALSE"]
    internal_wrappers = [r for r in data.get("solver_wrappers", []) if r.get("flag") == "FALSE"]
    user_wrappers = unique_by_name(sorted(user_wrappers, key=lambda x: x.get("name", "")))
    internal_wrappers = unique_by_name(sorted(internal_wrappers, key=lambda x: x.get("name", "")))
    solver_rows = []
    for r in user_wrappers:
        solver_rows.append([
            code(r.get("name", "")),
            code(r.get("flag", "")),
            format_default(r.get("default", "")),
            tex(r.get("description", "")),
        ])
    solver_table = longtable(["Attribute", "Input", "Default", "Description"], solver_rows, [r"p{0.24\linewidth}", r"p{0.10\linewidth}", r"p{0.22\linewidth}", r"p{0.37\linewidth}"], "User-facing SolidMechanics_MPM wrapper registrations from the current source.", "tab:solver-wrappers", size=r"\tiny")

    enum_rows = []
    for e in data.get("solver_enums", []):
        enum_rows.append([code(e.get("name", "")), tex(", ".join(e.get("values", [])))])
    enum_table = longtable(["Enumeration", "Values"], enum_rows, [r"p{0.43\linewidth}", r"p{0.50\linewidth}"], "Solver enumerations discovered in SolidMechanicsMPM.hpp.", "tab:solver-enums", size=r"\scriptsize")

    internal_names = ", ".join(r.get("name", "") for r in internal_wrappers)
    internal_para = ""
    if internal_names:
        internal_para = r"\paragraph{Internal/non-input wrappers.} The following registered wrappers were marked with \texttt{InputFlags::FALSE} in the reviewed source and are therefore treated as internal state rather than direct input controls: " + tex(internal_names) + ".\n"

    schema_parts = []
    for schema_name, rows in data.get("schema_tables", {}).items():
        schema_rows = []
        for r in rows:
            schema_rows.append([code(r.get("name", "")), code(r.get("type", "")), format_default(r.get("default", "")), tex(r.get("description", ""))])
        schema_parts.append(longtable(["Name", "Type", "Default", "Description"], schema_rows, [r"p{0.20\linewidth}", r"p{0.16\linewidth}", r"p{0.16\linewidth}", r"p{0.41\linewidth}"], f"Schema documentation table for {schema_name}.", f"tab:schema-{schema_name.replace('_', '-')}", size=r"\scriptsize"))

    safe_write(out_dir, "solver_attributes.tex", rf"""
\chapter{{Generated solver and schema reference}}
\label{{app:solver-attributes}}
\index{{SolidMechanics MPM!attributes}}
\index{{schema-generated documentation}}

This appendix is generated from solver wrapper registrations and schema-generated RST files.  It should be regenerated whenever input wrappers, defaults, or schema documentation change.

{enum_table}

{solver_table}

{internal_para}

\section{{Schema-generated reference tables}}
The following tables reproduce the existing schema-generated documentation snippets found for MPM-specific schema groups.

{''.join(schema_parts)}
""")

    # Events appendix.
    event_summary_rows = []
    event_attr_rows = []
    for e in sorted(data.get("event_data", []), key=lambda x: x.get("name", "")):
        attrs = [a for a in e.get("attributes", []) if a.get("flag") != "FALSE"]
        event_summary_rows.append([
            code(e.get("name", "")),
            code(e.get("class", "")),
            tex(e.get("description", "")),
            path(e.get("source", "")),
        ])
        for a in attrs:
            event_attr_rows.append([
                code(e.get("name", "")),
                code(a.get("name", "")),
                code(a.get("flag", "")),
                format_default(a.get("default", "")),
                tex(a.get("description", "")),
            ])

    event_summary = longtable(["Event", "Class", "Description", "Source"], event_summary_rows, [r"p{0.18\linewidth}", r"p{0.20\linewidth}", r"p{0.35\linewidth}", r"p{0.20\linewidth}"], "MPM event classes discovered in the current source.", "tab:event-summary", size=r"\scriptsize")
    event_attrs = longtable(["Event", "Attribute", "Input", "Default", "Description"], event_attr_rows, [r"p{0.17\linewidth}", r"p{0.17\linewidth}", r"p{0.11\linewidth}", r"p{0.15\linewidth}", r"p{0.33\linewidth}"], "MPM event attributes, excluding internal non-input state.", "tab:event-attrs", size=r"\scriptsize")
    safe_write(out_dir, "events.tex", rf"""
\chapter{{Generated MPM events catalogue}}
\label{{app:events}}
\index{{MPMEvents!catalogue}}

{event_summary}

{event_attrs}
""")

    # PFW appendix.
    pfw_rows = []
    for r in data.get("pfw_params", []):
        pfw_rows.append([code(r.get("name", "")), format_default(r.get("default", "")), tex("yes" if r.get("emitsSolverAttribute") else "no")])
    pfw_table = longtable(["PFW key", "Default", "Emits solver attribute"], pfw_rows, [r"p{0.40\linewidth}", r"p{0.32\linewidth}", r"p{0.18\linewidth}"], "ParticleFileWriter parameter keys and defaults from particleFileWriter.py.", "tab:pfw-params", size=r"\scriptsize")
    common = ", ".join(data.get("pfw_silo_common", []))
    all_fields = ", ".join(data.get("pfw_silo_all", []))
    safe_write(out_dir, "pfw.tex", rf"""
\chapter{{Generated ParticleFileWriter reference}}
\label{{app:pfw}}
\index{{ParticleFileWriter!parameters}}
\index{{Silo grid fields}}

{pfw_table}

\section{{Silo grid field presets}}
\paragraph{{Common preset.}} {tex(common)}.

\paragraph{{All preset.}} {tex(all_fields)}.
""")

    # Particle file format appendix.
    particle_rows = []
    for r in data.get("particle_columns", []):
        particle_rows.append([str(r.get("index", "")), code(r.get("name", "")), format_default(r.get("default", "")), tex("yes" if r.get("required") else "no")])
    particle_table = longtable(["Column", "Name", "Default", "Required if absent"], particle_rows, [r"p{0.10\linewidth}", r"p{0.39\linewidth}", r"p{0.28\linewidth}", r"p{0.15\linewidth}"], "Particle file field ordering and defaults from ParticleMeshGenerator.", "tab:particle-fields", size=r"\scriptsize")
    ptype_rows = [[str(i), code(v)] for i, v in enumerate(data.get("particle_types", []))]
    ptype_table = longtable(["Enum value", "Particle type"], ptype_rows, [r"p{0.20\linewidth}", r"p{0.70\linewidth}"], "Particle type enum values in the current source.", "tab:particle-types", size=r"\small")
    safe_write(out_dir, "particle_format.tex", rf"""
\chapter{{Generated particle-file reference}}
\label{{app:particle-format}}
\index{{particle file format}}
\index{{ParticleMesh}}

{ptype_table}

{particle_table}
""")

    # Geometry and materials appendix.
    geom_rows = []
    for r in data.get("geometry_objects", []):
        geom_rows.append([code(r.get("name", "")), tex(r.get("description", ""))])
    geom_table = longtable(["Geometry object", "Docstring summary"], geom_rows, [r"p{0.26\linewidth}", r"p{0.67\linewidth}"], "Geometry objects discovered in pfw_geometryObjects.py.", "tab:geometry-objects", size=r"\scriptsize")
    wrap_rows = []
    for r in data.get("geometry_wrappers", []):
        wrap_rows.append([code(r.get("name", "")), tex(r.get("description", ""))])
    wrap_table = longtable(["Wrapper", "Docstring summary"], wrap_rows, [r"p{0.28\linewidth}", r"p{0.65\linewidth}"], "Geometry wrappers discovered in pfw_geometryObjects.py.", "tab:geometry-wrappers", size=r"\scriptsize")
    mat_rows = []
    for r in data.get("material_docs", []):
        mat_rows.append([code(r.get("name", "")), tex(r.get("description", ""))])
    mat_table = longtable(["Material helper", "Docstring summary"], mat_rows, [r"p{0.30\linewidth}", r"p{0.63\linewidth}"], "Material helper functions discovered in pfw_materials.py.", "tab:material-helpers", size=r"\scriptsize")
    preset_rows = [[code(k), str(v)] for k, v in sorted(data.get("material_preset_counts", {}).items())]
    preset_table = longtable(["PFW material preset family", "Preset count"], preset_rows, [r"p{0.55\linewidth}", r"p{0.25\linewidth}"], "Material preset dictionary counts in pfw_materials.py.", "tab:material-presets", size=r"\small")
    util_rows = [[code(r.get("name", "")), tex(r.get("description", ""))] for r in data.get("geometry_utilities", [])]
    util_table = longtable(["Utility", "Docstring summary"], util_rows, [r"p{0.30\linewidth}", r"p{0.63\linewidth}"], "Selected geometry utility functions discovered in pfw_geometryObjects.py.", "tab:geometry-utils", size=r"\scriptsize")
    safe_write(out_dir, "geometry_materials.tex", rf"""
\chapter{{Generated geometry and material catalogue}}
\label{{app:geometry-materials}}
\index{{geometry catalogue}}
\index{{material catalogue}}

{geom_table}

{wrap_table}

{util_table}

{mat_table}

{preset_table}
""")

    # Suites appendix.
    suite_rows = []
    for suite_name in ["examples", "verification", "validation"]:
        for r in data.get("suite_cases", {}).get(suite_name, []):
            suite_rows.append([tex(suite_name), tex(r.get("family", "")), code(r.get("case", "")), tiny_path(r.get("path", ""))])
    suite_table = longtable(["Suite", "Family", "Case", "Input path"], suite_rows, [r"p{0.12\linewidth}", r"p{0.20\linewidth}", r"p{0.25\linewidth}", r"p{0.36\linewidth}"], "Discovered ParticleFileWriter suite input cases. Leading comment-block descriptions are kept in the linked suite reports.", "tab:suite-cases", size=r"\scriptsize")
    safe_write(out_dir, "suites.tex", rf"""
\chapter{{Generated suite case catalogue}}
\label{{app:suites}}
\index{{suite cases}}
\index{{verification cases}}
\index{{validation cases}}
\index{{example cases}}

{suite_table}
""")

    # Post-processing appendix.
    post_rows = []
    for p in data.get("post_scripts", []):
        name = os.path.basename(p)
        post_rows.append([code(name), path(p)])
    post_table = longtable(["Script", "Path"], post_rows, [r"p{0.35\linewidth}", r"p{0.58\linewidth}"], "Post-processing and suite analysis scripts discovered under ParticleFileWriter.", "tab:post-scripts", size=r"\scriptsize")
    safe_write(out_dir, "post_scripts.tex", rf"""
\chapter{{Generated post-processing script catalogue}}
\label{{app:post-scripts}}
\index{{post-processing scripts}}

{post_table}
""")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--in", dest="input_json", type=Path, default=Path("generated/data/geos_mpm_extracted.json"), help="metadata JSON produced by extract_mpm_metadata.py")
    parser.add_argument("--out", dest="out_dir", type=Path, default=Path("generated/tex"), help="directory for generated LaTeX files")
    args = parser.parse_args()
    data = json.loads(args.input_json.read_text(encoding="utf-8"))
    render(data, args.out_dir)


if __name__ == "__main__":
    main()
