set(CMAKE_C_COMPILER "${GCC_ROOT}/bin/gcc" CACHE PATH "" FORCE)
set(CMAKE_CXX_COMPILER "${GCC_ROOT}/bin/g++" CACHE PATH "" FORCE)
set(CMAKE_Fortran_COMPILER "${GCC_ROOT}/bin/gfortran" CACHE PATH "" FORCE)
set(ENABLE_FORTRAN OFF CACHE BOOL "" FORCE)
