set(ENABLE_MPI ON CACHE PATH "" FORCE)
set(MPI_ROOT "/vend/intel/parallel_studio_xe_2018_update3/compilers_and_libraries_2018.3.222/linux/mpi/intel64" CACHE PATH "" FORCE)
set(MPI_C_COMPILER "${MPI_ROOT}/bin/mpicc" CACHE PATH "" FORCE)
set(MPI_CXX_COMPILER "${MPI_ROOT}/bin/mpicxx" CACHE PATH "" FORCE)
set(MPI_Fortran_COMPILER "${MPI_ROOT}/bin/mpiifort" CACHE PATH "" FORCE)
set(MPIEXEC_EXECUTABLE "${MPI_ROOT}/bin/mpirun" CACHE PATH "" FORCE)
