import numpy
import re
import xml.etree.ElementTree as ElementTree
from geos.hdf5_wrapper import hdf5_wrapper

def getOutputFilesFromXML(xmlFilePath: str):
    """
    Extract the output file(s) generated by the PVTDrivers
    
    Args:
        xmlFilePath (str): Path to the xml file

    Returns:
        List[Tuple[str, str]]: List of tuples. First element is the name of the PVTDriver tag and
            the second is the path to the output file.
    """
    tree = ElementTree.parse(xmlFilePath)

    drivers = tree.findall("Tasks/PVTDriver")
    outputFiles = []
    for driver in drivers:
        if "output" in driver.attrib:
            outputFiles.append((driver.attrib["name"], driver.attrib["output"]))

    return outputFiles

def getColumnNames(xmlFilePath: str, driverName: str):
    """
    Extract the names for the columns reported in the output file(s)
    
    Args:
        xmlFilePath (str): Path to the xml file
        driverName (str): The name property of the PVTDriver xml element

    Returns:
        List[Tuple[str, str]]: List of tuples. First element is the column name, second element is
            the units. The first columns is the time column.
    """

    tree = ElementTree.parse(xmlFilePath)
    driver = [d for d in tree.findall("Tasks/PVTDriver") if d.attrib["name"] == driverName][0]
    
    # Find the corresponding fluid model
    fluidName = driver.attrib["fluid"]
    fluid = [c for c in tree.find("Constitutive") if c.attrib["name"] == fluidName][0]

    phaseNames = fluid.attrib["phaseNames"]
    phaseNames = re.sub("\{|\}", "", phaseNames)
    phaseNames = [s.strip() for s in phaseNames.split(",")]

    # Black oil models have no component names
    if fluid.tag in ["DeadOilFluid", "BlackOilFluid"]:
        componentNames = phaseNames
    else:
        componentNames = fluid.attrib["componentNames"]
        componentNames = re.sub("\{|\}", "", componentNames)
        componentNames = [s.strip() for s in componentNames.split(",")]

    outputCompressibility = False
    outputMassDensity = False
    outputPhaseComposition = False
    if "outputCompressibility" in driver.attrib:
        outputCompressibility = int(driver.attrib["outputCompressibility"]) != 0
    if "outputMassDensity" in driver.attrib:
        outputMassDensity = int(driver.attrib["outputMassDensity"]) != 0
    if "outputPhaseComposition" in driver.attrib:
        outputPhaseComposition = int(driver.attrib["outputPhaseComposition"]) != 0

    columns = []
    columns.append(("Time", "seconds"))
    columns.append(("Pressure", "Pa"))
    columns.append(("Temperature", "K"))
    columns.append(("Density", "kg/m3"))
    if outputCompressibility:
        columns.append(("Total Compressibility", "Pa^{-1}"))
    for phaseName in phaseNames:
        columns.append((f"Phase Fraction {phaseName}", "-"))
    for phaseName in phaseNames:
        columns.append((f"Phase Density {phaseName}", "kg/m3"))
    if outputMassDensity:
        for phaseName in phaseNames:
            columns.append((f"Phase Mass Density {phaseName}", "kg/m3"))
    for phaseName in phaseNames:
        columns.append((f"Phase Viscosity {phaseName}", "Pa s"))
    if outputPhaseComposition:
        for phaseName in phaseNames:
            for componentName in componentNames:
                columns.append((f"Phase Component Fraction {phaseName} {componentName}", "-"))

    return columns

def loadOutputData(fileName):
    """
    Load the physical data from the output text file
    
    Args:
        fileName (str): Path to the output text file

    Returns:
        numpy.ndarray: The data as a numpy array.
    """
    return numpy.loadtxt(fileName)

def get_all_curves(xmlFilePath: str):
    """
    List all the columns reported in all output file(s)
    
    Args:
        xmlFilePath (str): Path to the xml file

    Returns:
        List[str]: List of all the output columns from all PVTDriver tasks.
    """
    outputFiles = getOutputFilesFromXML(xmlFilePath)
    allColumns = []
    for driverName, _ in outputFiles:
        columns = getColumnNames(xmlFilePath, driverName)
        columnCount = len(columns)
        for c in range(1, columnCount):
            k = "%s %s" % (driverName, columns[c][0])
            allColumns.append((k,))

    return allColumns

def create_hdf5_file(xmlfile: str, filename: str):
    """
    Creates and hdf5 file from an xml file
    Collects all the data from the output text files and creates an hdf5 file. The data is split into
    the different properties.

    Args:
        xmlfile (str): Path to the input xml file
        fileName (str): Path to the output hdf5 file. This will be overwritten

    Returns:
        geos.hdf5_wrapper: The hdf5 wrapper for the data
    """
    
    outputFiles = getOutputFilesFromXML(xmlfile)
    
    hdf5 = hdf5_wrapper(filename, mode="w")

    for driverName, outputFile in outputFiles:
        columns = getColumnNames(xmlfile, driverName)
        columnCount = len(columns)
        fileData = loadOutputData(outputFile)
        assert fileData.shape[1] == columnCount

        timeColumn = 0

        for c in range(1, columnCount):
            k = "%s %s" % (driverName, columns[c][0])
            hdf5[k] = fileData[:,c]
            k += " Time"
            hdf5[k] = fileData[:,timeColumn]
            k += " ReferencePosition"
            hdf5[k] = 0.0

    return hdf5

def create_plots(xmlFilePath: str, hdfFilePath: str, plotDirectory: str):
    create_hdf5_file(xmlfile=xmlFilePath, filename=hdfFilePath)

if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser()
    parser.add_argument( "xmlfile", help="Path to the input xml file" )
    parser.add_argument( "hdf5file", help="Path to the hdf5 file to create" )
    args = parser.parse_args()

    create_hdf5_file(
        xmlfile=args.xmlfile,
        filename=args.hdf5file
    )

