#!/usr/bin/env python3
"""Generic post-processing for staged MPM example runs.

The runProblem wrapper copies this script and any case-specific visitRender_*.py
script into the Lustre run directory.  This script then runs VisIt in CLI mode,
copies any generated PNG/CSV/JSON/log products back to the source example
output directory, and leaves useful logs even when rendering fails.
"""
from __future__ import annotations

import argparse
import glob
import os
import shutil
import signal
import subprocess
import sys
import textwrap
from datetime import datetime
from pathlib import Path


def log_line(handle, message: str) -> None:
    print(message, flush=True)
    handle.write(message + "\n")
    handle.flush()


def find_visit_command() -> str | None:
    candidates = []
    env = os.environ.get("VISIT_COMMAND")
    if env:
        candidates.append(env)
    candidates.extend(["/usr/gapps/visit/bin/visit", "visit"])
    for cmd in candidates:
        if os.path.isabs(cmd) and os.path.exists(cmd):
            return cmd
        found = shutil.which(cmd)
        if found:
            return found
    return None


def find_renderer(run_dir: Path, case_name: str, output_prefix: str) -> Path | None:
    candidates = [
        run_dir / f"visitRender_{case_name}.py",
        run_dir / f"visitRender_{output_prefix}.py",
        run_dir / f"visitRender_{case_name.replace('-', '_')}.py",
        run_dir / f"visitRender_{output_prefix.replace('-', '_')}.py",
    ]
    # Case aliases used by example suite.
    if case_name == "borehole_Ghareb":
        candidates.append(run_dir / "visitRender_borehole_Ghareb.py")
    for p in candidates:
        if p.exists():
            return p
    matches = sorted(run_dir.glob("visitRender_*.py"))
    if matches:
        return matches[0]
    return None


def write_visit_driver(driver: Path, renderer: Path, renderer_args: list[str]) -> None:
    # The key detail is exec(..., globals(), globals()).  VisIt injects functions
    # such as OpenDatabase, AddPlot, DrawPlots, SaveWindow into the driver global
    # namespace.  runpy.run_path creates a fresh namespace, so those functions are
    # not visible to the renderer and OpenDatabase appears unavailable.
    content = """# Auto-generated by mpm_example_postprocess.py\n"""
    content += f"RENDERER = {str(renderer)!r}\n"
    content += f"ARGS = {renderer_args!r}\n"
    content += """
import sys
sys.argv = [RENDERER] + ARGS
with open(RENDERER, 'r', encoding='utf-8') as _fh:
    _code = compile(_fh.read(), RENDERER, 'exec')
exec(_code, globals(), globals())
"""
    driver.write_text(content)


def run_with_timeout(cmd: list[str], cwd: Path, timeout: int, log_path: Path, handle) -> int:
    log_line(handle, "Running command: " + " ".join(cmd))
    with log_path.open("w") as lf:
        lf.write("Command: " + " ".join(cmd) + "\n")
        lf.flush()
        proc = subprocess.Popen(
            cmd,
            cwd=str(cwd),
            stdout=lf,
            stderr=subprocess.STDOUT,
            text=True,
            preexec_fn=os.setsid,
        )
        try:
            return proc.wait(timeout=timeout)
        except subprocess.TimeoutExpired:
            lf.write(f"\nTIMEOUT after {timeout} seconds. Killing process group.\n")
            lf.flush()
            try:
                os.killpg(proc.pid, signal.SIGTERM)
            except Exception:
                pass
            try:
                proc.wait(timeout=15)
            except subprocess.TimeoutExpired:
                try:
                    os.killpg(proc.pid, signal.SIGKILL)
                except Exception:
                    pass
                proc.wait()
            return 124


def copy_products(run_dir: Path, frames_dir: Path, output_dir: Path, handle) -> int:
    output_dir.mkdir(parents=True, exist_ok=True)
    patterns = [
        frames_dir / "*.png", frames_dir / "*.csv", frames_dir / "*.json", frames_dir / "*.log",
        run_dir / "*.png", run_dir / "*.csv", run_dir / "*.json", run_dir / "*.log",
        run_dir / "reactionHistory.csv", run_dir / "boxAverageHistory.csv",
    ]
    copied = 0
    seen: set[Path] = set()
    for pat in patterns:
        for src_s in glob.glob(str(pat)):
            src = Path(src_s)
            if not src.is_file() or src in seen:
                continue
            seen.add(src)
            dst = output_dir / src.name
            try:
                shutil.copy2(src, dst)
                copied += 1
                log_line(handle, f"Copied product: {src.name}")
            except Exception as exc:
                log_line(handle, f"WARNING: failed to copy {src}: {exc}")
    if copied == 0:
        log_line(handle, "WARNING: no products were copied")
        for sub in [run_dir, frames_dir]:
            if sub.exists():
                listing = sorted(p.name for p in sub.iterdir())[:80]
                log_line(handle, f"Listing {sub}: " + ", ".join(listing))
    return copied


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-dir", required=True)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--case-name", required=True)
    parser.add_argument("--output-prefix", default=None)
    parser.add_argument("--job-id", default=None)
    parser.add_argument("--skip-slurm-check", action="store_true")
    parser.add_argument("--force", "-y", action="store_true")
    parser.add_argument("--skip-render", action="store_true")
    parser.add_argument("--copy-only", action="store_true")
    parser.add_argument("--visit-timeout", type=int, default=600)
    parser.add_argument("--visit-list-databases", action="store_true")
    parser.add_argument("--initial-variable", default=None)
    parser.add_argument("--final-variable", default=None)
    parser.add_argument("--view", default=None)
    parser.add_argument("--mesh", default="CellRegion1")
    args, extra = parser.parse_known_args()

    run_dir = Path(args.run_dir).expanduser().resolve()
    output_dir = Path(args.output_dir).expanduser().resolve()
    frames_dir = run_dir / "visit_frames"
    frames_dir.mkdir(parents=True, exist_ok=True)
    output_prefix = args.output_prefix or args.case_name

    post_log = run_dir / f"{output_prefix}_postprocess.log"
    visit_log = run_dir / f"{output_prefix}_visit_render.log"

    with post_log.open("w") as log:
        log_line(log, "Postprocess started at " + datetime.now().isoformat(timespec="seconds"))
        log_line(log, f"Run directory: {run_dir}")
        log_line(log, f"Output directory: {output_dir}")
        log_line(log, f"Visit frames directory: {frames_dir}")
        if args.skip_slurm_check:
            log_line(log, "Skipping GEOS Slurm-output check")
        else:
            log_line(log, "GEOS Slurm-output check is not enforced by this generic postprocessor")

        visit_rc = 0
        if not args.skip_render and not args.copy_only:
            visit_cmd = find_visit_command()
            if not visit_cmd:
                log_line(log, "WARNING: VisIt command not found; copying existing products only")
                visit_rc = 127
            else:
                renderer = find_renderer(run_dir, args.case_name, output_prefix)
                if not renderer:
                    log_line(log, "WARNING: no visitRender_*.py renderer found; copying existing products only")
                    visit_rc = 126
                else:
                    renderer_args = [
                        "--run-dir", str(run_dir),
                        "--output-dir", str(frames_dir),
                        "--case-name", args.case_name,
                        "--states", "initial,final",
                    ]
                    if args.mesh:
                        renderer_args += ["--mesh", args.mesh]
                    if args.view:
                        renderer_args += ["--view", args.view]
                    if args.initial_variable:
                        renderer_args += ["--initial-variable", args.initial_variable]
                    if args.final_variable:
                        renderer_args += ["--final-variable", args.final_variable]
                    if args.visit_list_databases:
                        renderer_args += ["--list-databases"]
                    renderer_args += extra
                    driver = run_dir / f"{output_prefix}_visit_driver.py"
                    write_visit_driver(driver, renderer, renderer_args)
                    cmd = [visit_cmd, "-nowin", "-cli", "-s", str(driver)]
                    log_line(log, f"Using VisIt command: {visit_cmd}")
                    log_line(log, f"Running custom VisIt renderer through driver: {driver}")
                    visit_rc = run_with_timeout(cmd, run_dir, args.visit_timeout, visit_log, log)
                    log_line(log, f"VisIt return code: {visit_rc}")
        else:
            log_line(log, "Skipping rendering; copy-only mode")

        copied = copy_products(run_dir, frames_dir, output_dir, log)
        try:
            shutil.copy2(post_log, output_dir / post_log.name)
        except Exception:
            pass
        try:
            if visit_log.exists():
                shutil.copy2(visit_log, output_dir / visit_log.name)
        except Exception:
            pass

        # Do not fail if VisIt wrote valid products but returned nonzero during cleanup.
        pngs = list(output_dir.glob("*.png"))
        if visit_rc != 0 and not pngs:
            return visit_rc
        return 0


if __name__ == "__main__":
    raise SystemExit(main())
