# -*- coding: utf-8 -*-
"""
Created on Wed Mar 1 09:00:00 2017

@author: homel1, crook5

Script to automate generation of a GEOS-MPM input file and particle file
based on geometric objects.
"""

from __future__ import print_function    # (at top of module)
from __future__ import division
from __future__ import unicode_literals
import numpy as np                   # math stuff
from sklearn.neighbors import KDTree # nearest neighbor search with KDTree
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import time
import datetime                               # used for date stamp
import os                                     # operating sys commands, pwd, etc.
import subprocess                             # lets you call msub and get jobid
import sys                                    # to access command arguments.
import shutil
import importlib
import pathlib
import random                                 # used to define a random material type
import pfw_geometryObjects as geom            # this contains all the geometry object functions for pfw
import math
import getpass
import platform
import argparse
import re

parser = argparse.ArgumentParser(description='Particle File Writer for GEOS-MPM')
parser.add_argument('input_file', help="PFW input file", type=str)
args = parser.parse_args()

# ============================================================================================
# BEGIN FUNCTION DEFINITIONS
# ============================================================================================

# Silo grid-field presets for pfw_input convenience. These are output-only
# controls for the Silo block generated by PFW; they are deliberately separate
# from the SolidMechanics_MPM solver attributes.
_PFW_SILO_COMMON_GRID_FIELDS = [
  "gridMass",
  "gridVelocity",
  "gridInternalForce",
  "gridDamageGradient",
]

_PFW_SILO_ALL_GRID_FIELDS = [
  "gridCohesiveNode",
  "gridSurfaceMass",
  "gridSurfaceFieldMass",
  "gridExplicitSurfaceNormal",
  "gridPrincipalExplicitSurfaceNormal",
  "gridCohesiveFieldFlag",
  "gridMaxMappedParticleID",
  "gridCohesiveArea",
  "gridCohesiveForce",
  "gridReferenceSurfacePosition",
  "gridReferenceMaterialVolume",
  "gridReferenceAreaVector",
  "gridDisplacement",
  "gridCenterOfVolume",
  "gridParticleMappedSurfaceNormal",
  "gridMass",
  "gridActive",
  "gridMaterialVolume",
  "gridUncontactedVelocity",
  "gridVelocity",
  "gridDVelocity",
  "gridMomentum",
  "gridAcceleration",
  "gridExternalForce",
  "gridSurfaceTensionForce",
  "gridInternalForce",
  "gridContactForce",
  "gridDamage",
  "gridDamageGradient",
  "gridMaxDamage",
  "gridFieldGradientAlignment",
]

_PFW_SILO_GRID_FIELD_PRESETS = {
  "": [],
  "0": [],
  "false": [],
  "none": [],
  "off": [],
  "no": [],
  "basic": _PFW_SILO_COMMON_GRID_FIELDS,
  "common": _PFW_SILO_COMMON_GRID_FIELDS,
  "default": _PFW_SILO_COMMON_GRID_FIELDS,
  "on": _PFW_SILO_COMMON_GRID_FIELDS,
  "true": _PFW_SILO_COMMON_GRID_FIELDS,
  "1": _PFW_SILO_COMMON_GRID_FIELDS,
  "all": _PFW_SILO_ALL_GRID_FIELDS,
  "all_mpm": _PFW_SILO_ALL_GRID_FIELDS,
  "all-mpm": _PFW_SILO_ALL_GRID_FIELDS,
}


def _split_geos_name_list_string(value):
  """Split a PFW/GEOS name-list string into names."""
  text = str(value).strip()
  if not text:
    return []

  if ( text.startswith("{") and text.endswith("}") ) or \
     ( text.startswith("[") and text.endswith("]") ) or \
     ( text.startswith("(") and text.endswith(")") ):
    text = text[1:-1].strip()

  if not text:
    return []

  rawTokens = text.split(",") if "," in text else text.split()
  return [ token.strip().strip("'\"") for token in rawTokens if token.strip().strip("'\"") ]


def _dedupe_preserving_order(values):
  seen = set()
  result = []
  for value in values:
    if value not in seen:
      result.append(value)
      seen.add(value)
  return result


def _normalize_silo_grid_field_names(value):
  """Normalize a pfw_input Silo grid-field request to wrapper names.

  Supported current PFW forms include:
    pfw["gridFieldNames"] = ["gridMass", "gridVelocity"]
    pfw["siloGridFieldNames"] = "{ gridMass, gridVelocity }"
    pfw["siloGridFields"] = "common" or True
    pfw["siloGridFields"] = "all"
  """
  if value is None or value is False:
    return []
  if value is True:
    return list(_PFW_SILO_COMMON_GRID_FIELDS)

  if isinstance(value, str):
    tokens = _split_geos_name_list_string(value)
  elif isinstance(value, (list, tuple, set)):
    tokens = list(value)
  else:
    tokens = [value]

  values = []
  for token in tokens:
    if token is None or token is False:
      continue
    if token is True:
      values.extend(_PFW_SILO_COMMON_GRID_FIELDS)
      continue

    text = str(token).strip().strip("'\"")
    if not text:
      continue

    nestedTokens = _split_geos_name_list_string(text)
    if len(nestedTokens) > 1:
      values.extend(_normalize_silo_grid_field_names(nestedTokens))
      continue

    preset = text.lower()
    if preset in _PFW_SILO_GRID_FIELD_PRESETS:
      values.extend(_PFW_SILO_GRID_FIELD_PRESETS[preset])
    else:
      values.append(text)

  return _dedupe_preserving_order(values)


def _resolve_pfw_silo_grid_field_names(pfwDict):
  """Resolve all supported PFW aliases for requested Silo grid fields."""
  aliasKeys = ("gridFieldNames", "siloGridFieldNames", "siloGridFields")
  requested = []
  usedAliases = []

  for key in aliasKeys:
    if key in pfwDict:
      fieldNames = _normalize_silo_grid_field_names(pfwDict[key])
      if fieldNames:
        requested.extend(fieldNames)
        usedAliases.append(key)

  requested = _dedupe_preserving_order(requested)
  if requested:
    print("Silo grid-field output requested from pfw_input using " + ", ".join(usedAliases) + ":")
    print("  " + ", ".join(requested))
  return requested


def _format_geos_name_array(values):
  """Format names as a GEOS XML groupNameRef_array value."""
  names = _dedupe_preserving_order([ str(value).strip() for value in values if str(value).strip() ])
  if any(not name for name in names):
    raise ValueError('GEOS name array contains an empty name')
  return "{ " + ", ".join(names) + " }" if names else "{}"


def _format_solver_child_xml_block(tagName, value, indent="\t\t\t"):
  """Format an explicit user-provided XML child block under SolidMechanics_MPM.

  This is intentionally a formatter only: particleFileWriter.py assumes the
  supplied XML is current and does not perform legacy schema migrations here.
  Use pfw_inputFixer.py to modernize obsolete inputs before running PFW.
  """
  if value is None or value == [] or value == "":
    return ""
  if isinstance(value, (list, tuple)):
    body = "\n".join(str(v).strip() for v in value if str(v).strip())
  else:
    body = str(value).strip()
  if not body:
    return ""

  body = re.sub(r"^\s*<" + re.escape(tagName) + r"\b[^>]*>\s*", "", body, flags=re.S)
  body = re.sub(r"\s*</" + re.escape(tagName) + r">\s*$", "", body, flags=re.S)
  body = body.strip()
  if not body:
    return ""

  childIndent = indent + "\t"
  return "\n" + indent + f"<{tagName}>\n" + childIndent + ("\n" + childIndent).join(body.splitlines()) + "\n" + indent + f"</{tagName}>\n"


# ============================================================================================
# END FUNCTION DEFINITIONS
# ============================================================================================

# ============================================================================================
# MACHINE-SPECIFIC Calculations.
# ============================================================================================


# List of cores per node of LC (or other) machines.  
machineList = {
  'tuolumne':96,
  'dane':112,
  'rzhound':56,
  'tioga':64
}

# Number of GEOS MPI ranks to place on each node for generated job scripts.
# CPU-only machines keep the legacy cores-per-node value.  On Tuolumne the
# intended device launch is one MPI rank per MI300A APU/GPU.
ranksPerNodeList = {
  'tuolumne':4,
  'dane':112,
  'rzhound':56,
  'tioga':64
}

node = platform.node()
nodeLower = node.lower()
machine = 'unknown'
coresPerNode = 1
ranksPerNode = 1
for key, value in machineList.items():
  keyMatchesNode = key in nodeLower or ( key == 'tuolumne' and nodeLower.startswith( 'tuo' ) )
  if keyMatchesNode:
    machine = key
    coresPerNode = value
    ranksPerNode = ranksPerNodeList.get( key, value )
    # This could be unsafe if someone added a machines name we use elsewhere.
    # Currently we test if tuolumne=True for various MPI tasks.
    exec(key+'=True')
  else:
    exec(key+'=False')

# Check if machine uses Flux scheduler otherwise assume SLURM
flux = True if machine == 'tuolumne' else False

# # MPI specific variables
# there seems to be an issue with mpi4py and subprocess launching 
# slurm scripts that include srun. We've included the '#SBATCH --export=NONE' command
# in launched scripts below, which seems to fix it, but be aware there may be
# issues when launching subprocesses from this script, even if no MPI commands are used
# or if num_ranks=0.
#
if flux:
  rank = 0
  num_ranks = 1
else:
  from mpi4py import MPI
  comm = MPI.COMM_WORLD # gets communication pool 
  rank = comm.Get_rank()  # gets rank of current process 
  num_ranks = comm.Get_size() # total number of processes


# There are places where we compare numpy array to string, currently works, might not in the future
# fix it, but for now so we don't spam the log file:
# https://stackoverflow.com/questions/40659212/futurewarning-elementwise-comparison-failed-returning-scalar-but-in-the-futur
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)


# ===========================================
# READ FROM USER USER DEFS FILE
# ===========================================


username = getpass.getuser()
userDefsFile = str('userDefs_'+str(username))

if not pathlib.Path(userDefsFile + ".py").is_file():
  candidates = sorted(pathlib.Path(".").glob("userDefs_*.py"))
  if len(candidates) == 1:
    userDefsFile = candidates[0].stem
  else:
    names = ", ".join(str(p) for p in candidates) if candidates else "none found"
    raise FileNotFoundError(
      "Could not find " + userDefsFile + ".py in the current run directory. "
      "Copy your userDefs_<user>.py into the run directory or run through the example runProblem wrapper. "
      "Available userDefs files: " + names)

userDefs = importlib.import_module(userDefsFile)

def _expand_user_path(value):
  return os.path.abspath(os.path.expandvars(os.path.expanduser(str(value))))


def _resolve_input_file_arg(inputFileArg):
  """Return the concrete PFW input path supplied on the command line."""
  rawArg = str(inputFileArg).strip()
  if not rawArg:
    raise ValueError("PFW input file argument is empty")
  inputPath = pathlib.Path(os.path.expandvars(os.path.expanduser(rawArg)))
  if not inputPath.is_absolute():
    inputPath = pathlib.Path.cwd() / inputPath
  inputPath = inputPath.resolve()
  if inputPath.suffix != ".py":
    raise ValueError("PFW input file must be a Python file ending in .py: " + str(inputPath))
  if not inputPath.is_file():
    raise FileNotFoundError("PFW input file not found: " + str(inputPath))
  return inputPath


def _read_input_source_dir(defaultInputDir):
  """Return the directory used as the base for input-relative dependencies.

  runClean scripts can set PFW_INPUT_SOURCE_DIR or write .pfw_input_source_dir
  when they stage an input file from an external case directory.  For direct
  particleFileWriter.py runs, fall back to the directory containing the input
  file that was passed on the command line.
  """
  envValue = os.environ.get("PFW_INPUT_SOURCE_DIR", "").strip()
  if envValue:
    return pathlib.Path(_expand_user_path(envValue))

  marker = pathlib.Path(".pfw_input_source_dir")
  if marker.is_file():
    markerValue = marker.read_text().strip()
    if markerValue:
      return pathlib.Path(_expand_user_path(markerValue))

  return pathlib.Path(defaultInputDir).resolve()


def _strip_optional_quotes(value):
  text = str(value).strip()
  if len(text) >= 2 and text[0] == text[-1] and text[0] in ("'", '"'):
    return text[1:-1]
  return text


def _parse_pfw_dependency_line(line):
  """Parse a #[pfw_dependency] line.

  Supported forms are:
    #[pfw_dependency] file.dat
    #[pfw_dependency] input:tables/file.dat
    #[pfw_dependency] pfw:pfw_materials.py
    #[pfw_dependency] /full/path/to/file.dat
    #[pfw_dependency] input:tables/file.dat => tables/file.dat
  """
  match = re.match(r"^\s*#\s*\[pfw_dependency\]\s*(.*?)\s*$", line)
  if match is None:
    return None

  spec = match.group(1).strip()
  if not spec:
    return None

  if "=>" in spec:
    sourceSpec, destSpec = spec.split("=>", 1)
    return _strip_optional_quotes(sourceSpec), _strip_optional_quotes(destSpec)

  return _strip_optional_quotes(spec), None


def _unique_paths(paths):
  unique = []
  seen = set()
  for path in paths:
    key = str(path)
    if key not in seen:
      unique.append(path)
      seen.add(key)
  return unique


def _resolve_dependency_source(sourceSpec, inputSourceDir, pfwPath):
  """Resolve a dependency declared by a #[pfw_dependency] source line.

  Relative paths are interpreted relative to the pfw_input file.  Prefix a path
  with input: or pfw: to choose the input directory or PFW support directory
  explicitly.  Absolute paths are used as written.
  """
  expanded = os.path.expandvars(os.path.expanduser(str(sourceSpec).strip()))
  inputBase = pathlib.Path(inputSourceDir)
  pfwBase = pathlib.Path(pfwPath)

  if expanded.startswith("input:"):
    candidate = inputBase / expanded[len("input:"):].lstrip("/")
  elif expanded.startswith("pfw:"):
    candidate = pfwBase / expanded[len("pfw:"):].lstrip("/")
  elif os.path.isabs(expanded):
    candidate = pathlib.Path(expanded)
  else:
    candidate = inputBase / expanded

  candidate = pathlib.Path(_expand_user_path(candidate)).resolve()
  if candidate.is_file():
    return candidate

  raise FileNotFoundError(
    "Could not resolve #[pfw_dependency] entry '" + str(sourceSpec) + "'. Tried:\n  " + str(candidate))


def _safe_dependency_destination(sourceSpec, destSpec):
  """Return a safe run-directory-relative copy destination."""
  if destSpec is not None:
    destination = pathlib.Path(str(destSpec).strip())
    if str(destination) == "" or destination.is_absolute() or ".." in destination.parts:
      raise ValueError(
        "Invalid #[pfw_dependency] destination '" + str(destSpec) +
        "'. Destination must be relative to the run directory and must not contain '..'.")
    return destination

  basenameSpec = str(sourceSpec).strip()
  if basenameSpec.startswith("input:"):
    basenameSpec = basenameSpec[len("input:"):]
  elif basenameSpec.startswith("pfw:"):
    basenameSpec = basenameSpec[len("pfw:"):]

  basename = os.path.basename(basenameSpec.rstrip("/"))
  if basename == "":
    raise ValueError("Invalid #[pfw_dependency] entry with empty destination: " + str(sourceSpec))
  return pathlib.Path(basename)


def _stage_dependency_file(sourcePath, destinationPath):
  destinationPath.parent.mkdir(parents=True, exist_ok=True)
  temporaryPath = destinationPath.with_name(destinationPath.name + ".temp")
  shutil.copyfile(str(sourcePath), str(temporaryPath))
  os.rename(str(temporaryPath), str(destinationPath))

  # Defend against stale metadata on Lustre filesystems, which has caused
  # intermittent import failures immediately after a dependency was copied.
  deadline = time.time() + 5.0
  while time.time() < deadline:
    if destinationPath.exists() and destinationPath.stat().st_size > 0:
      break
    time.sleep(0.05)


geosPath = _expand_user_path(userDefs.geosPath)
pfwPath = _expand_user_path(userDefs.pfwPath)


# inputFile is a filesystem-safe label derived from the provided file path.
inputFilePath = _resolve_input_file_arg(args.input_file)
inputFile = inputFilePath.stem.replace('.', '_')

# Make both the run directory and the input-file directory importable.  The run
# directory is kept first so staged dependencies override files from the source
# input directory.
currentDirectory = str(pathlib.Path.cwd().resolve())
inputFileDirectory = str(inputFilePath.parent.resolve())
if currentDirectory not in sys.path:
  sys.path.insert(0, currentDirectory)
if inputFileDirectory != currentDirectory and inputFileDirectory not in sys.path:
  sys.path.insert(1, inputFileDirectory)


# ===========================================
# COPY DEPENDENCIES
# ===========================================

# Before importing the input file, check for extra files listed with
# #[pfw_dependency].  Relative dependencies are resolved relative to the original
# input-file directory first and userDefs.pfwPath second.  A dependency can force
# a base directory with input:<path> or pfw:<path>, and absolute paths are also
# accepted.  Optional copy destinations use "=>" and are always relative to the
# run directory.
inputSourceDir = _read_input_source_dir(inputFilePath.parent)
dependencyCopies = []
with open(str(inputFilePath), "r") as fileText:
  for lineNumber, line in enumerate(fileText, start=1):
    parsed = _parse_pfw_dependency_line(line)
    if parsed is None:
      continue

    sourceSpec, destSpec = parsed
    sourcePath = _resolve_dependency_source(sourceSpec, inputSourceDir, pfwPath)
    destinationPath = _safe_dependency_destination(sourceSpec, destSpec)
    dependencyCopies.append((sourcePath, destinationPath))

print("Dependency files to be copied:")
if dependencyCopies:
  for sourcePath, destinationPath in dependencyCopies:
    print("  ", sourcePath, " -> ", destinationPath)
else:
  print("   <none>")

copyDestinationRoot = pathlib.Path(".")
if rank == 0:
  copyDestinationRoot.mkdir(parents=True, exist_ok=True)
  for sourcePath, destinationPath in dependencyCopies:
    _stage_dependency_file(sourcePath, copyDestinationRoot / destinationPath)

# Make sure rank 0 finishes staging dependencies before other ranks import the
# input file.  Under Flux PFW is currently run serially, so there is no MPI
# communicator to synchronize.
if not flux:
  comm.Barrier()

# ===========================================
# READ INPUT FILE AND IMPORT PFW DICTIONARY
# ===========================================
# Before importing we clear caches that might store out-dated metadata on the available
# files, resulting in failure of imports of dependencies within the inputfile.
importlib.invalidate_caches()


# Import the exact input file that was passed on the command line.
spec = importlib.util.spec_from_file_location(inputFile, str(inputFilePath))
if spec is None or spec.loader is None:
  raise ImportError("Could not load PFW input file: " + str(inputFilePath))
job = importlib.util.module_from_spec(spec)
sys.modules[inputFile] = job
spec.loader.exec_module(job)

# file name prefix is date stamped
now = datetime.datetime.now()
timeStamp = str(now.year)[-2:]+str(now.month).zfill(2)+str(now.day).zfill(2) + \
            str(now.hour).zfill(2)+str(now.minute).zfill(2)+str(now.second).zfill(2)

# Current working directory
PWD = os.getcwd()

# Variable Info
# sortObjects: This is useful for large simulations with many object.  It constructs a subset of objects
#              for each slice, and only searches those. For granular asseblies of objects this should be
#              much faster.  Not all objects have the necessary xmin and xmax attribute, so this isnn't
#              default behavior.  This shouldn't change order of objects for first-in priority.


# If a specific variable needs a check before being written to solver string a handle to that function is added as a value in the dictionary below
# Value contains ( default value, flag to include in xml mpm solver parameter string if not specified or not )
parameters = {
               'allowNonConvergedLinearSolverSolution': ( None, True ),  # MPM: accept failed linear solve solution instead of cutting dt.
               'areaIntegrationMethod': ( None, True ),  # MPM: method for nodal area integration.
               'autoRestart': ( False, False ),  # PFW: generate auto-restart job logic.
               'bcTable': ( None, True ),  # MPM: time-dependent boundary-condition type table.
               'binSizeMultiplier': ( None, True ),  # MPM: neighbor/bin size multiplier.
               'bodyForce': ( None, True ),  # MPM: uniform body-force vector.
               'boundaryConditionTypes': ( None, True ),  # MPM: boundary condition type on each domain face.
               'boundaryFaceCoefficientsOfRestitution': ( None, True ),  # MPM: wall restitution coefficients by face.
               'boundaryFaceFrictionCoefficients': ( None, True ),  # MPM: wall friction coefficients by face.
               'boxAverageHistory': ( None, True ),  # MPM: enable box-average history output.
               'boxAverageMax': ( None, True ),  # MPM: box-average maximum corner.
               'boxAverageMin': ( None, True ),  # MPM: box-average minimum corner.
               'boxAverageResizeWithDomain': ( None, True ),  # MPM: resize box-average region with domain deformation.
               'boxAverageWriteInterval': ( None, True ),  # MPM: box-average write interval.
               'caseName': ( '', False ),  # PFW: case/job name override.
               'cflFactor': ( None, True ),  # MPM: CFL time-step factor.
               'computeInternalEnergyAndTemperature': ( None, True ),  # MPM: thermal-state update compatibility flag.
               'computeNodalArea': ( None, True ),  # MPM: compute nodal areas from surface geometry.
               'computeParticleSurfaceNormalsAndPositions': ( None, True ),  # MPM: compute particle surface normals/positions.
               'computeSPHJacobian': ( None, True ),  # MPM: compute SPH Jacobian for overlap correction.
               'cohesiveFieldPartitioning': ( None, False ),  # PFW/CZ legacy convenience key; not a solver XML attribute.
               'cohesiveLaw': ( None, False ),  # PFW/CZ legacy convenience key; not a solver XML attribute.
               'contactGapCorrection': ( None, True ),  # MPM: enable contact-gap mitigation.
               'contactNormalExponent': ( None, True ),  # MPM: exponent for weighted contact normals.
               'contactNormalType': ( None, True ),  # MPM: contact-normal construction mode.
               'cpdiDomainScaling': ( None, True ),  # MPM: CPDI domain-scaling option.
               'crackTipDetectionThreshold': ( None, True ),  # MPM: crack-tip detection threshold.
               'damageFieldPartitioning': ( None, True ),  # MPM: partition velocity fields using damage gradients.
               'dependencies': ( [], False ),  # PFW: files to stage beside generated input.
               'directionalOverlapCorrection': ( None, True ),  # MPM: directional correction for particle pile-up.
               'disableSurfaceNormalsAndPositionsOnCPDIScaling': ( None, True ),  # MPM: drop explicit surfaces after CPDI scaling.
               'disableSurfaceNormalsAndPositionsOnDamage': ( None, True ),  # MPM: drop explicit surfaces after damage.
               'enableContact': ( None, True ),  # MPM: enable contact between velocity fields.
               'enablePrescribedBoundaryTransverseVelocities': ( None, True ),  # MPM: enable transverse boundary velocities.
               'enableSurfaceTension': ( None, True ),  # MPM: enable particle surface-tension force.
               'endTime': ( 1.0, False ),  # PFW: simulation end time for generated event.
               'exactJIntegration': ( None, True ),  # MPM: enforce exact J integration for F updates.
               'explicitSurfaceNormalInfluence': ( None, True ),  # MPM: weight explicit vs implicit surface normals.
               'frictionCoefficient': ( None, True ),  # MPM: global friction coefficient.
               'frictionCoefficientTable': ( None, True ),  # MPM: friction coefficients by contact group.
               'frictionCoefficientRuleOfMixtures': ( None, True ),  # MPM: rule of mixtures for friction coefficient.
               'FSubcycles': ( None, True ),  # MPM: deformation-gradient integration subcycles.
               'flagParticlesWithBadMappingArraysForDeletion': ( None, True ),  # MPM: delete/compact particles whose map stencils are out of bounds.
               'fTable': ( None, True ),  # MPM: time-dependent global stretch/deformation table.
               'fTableInterpType': ( None, True ),  # MPM: interpolation type for fTable.
               'generalizedVortexMMS': ( None, True ),  # MPM: generalized-vortex MMS option.
               'generateParticleFile': ( True, False ),  # PFW: write particle file when true.
               'gpuScheme': ( None, True ),  # MPM: GPU execution scheme.
               'gridFieldNames': ( [], False ),  # PFW: Silo grid fields to write.
               'siloGridFieldNames': ( None, False ),  # PFW: alias for Silo grid fields to write.
               'siloGridFields': ( None, False ),  # PFW: Silo grid-field preset/list alias.
               'initialDt': ( None, True ),  # MPM: initial solver time step.
               'lastRestartBufferInSeconds': ( 10, False ),  # PFW: wall-clock buffer before final restart.
               'LBar': ( None, True ),  # MPM: L-bar stabilization mode.
               'LBarScale': ( None, True ),  # MPM: L-bar stabilization scale.
               'logLevel': ( None, True ),  # GEOS: solver log-level override.
               'logMomentum': ( None, True ),  # MPM: log momentum balance diagnostics.
               'logStartCycle': ( None, True ),  # MPM: first cycle for diagnostic logging.
               'LRtolerance': ( None, True ),  # MPM: logistic-regression tolerance.
               'materialPropertyString': ( None, False ),  # PFW: explicit material XML string.
               'materials': ( None, False ),  # PFW: material dictionaries/objects for particle assignment.
               'maxLRIterations': ( None, True ),  # MPM: max logistic-regression iterations.
               'maxParticleJacobian': ( None, True ),  # MPM: delete particles above this Jacobian.
               'maxParticleVelocity': ( 10.0, True ),  # MPM: delete particles above this velocity.
               'mBank': ( None, False ),  # PFW: batch-account/bank name.
               'mBatch': ( True, False ),  # PFW: generate a batch script.
               'mCores': ( 1, False ),  # PFW: requested cores/ranks.
               'minParticleJacobian': ( None, True ),  # MPM: delete particles below this Jacobian.
               'mPartition': ( 'pbatch', False ),  # PFW: batch partition/queue.
               'mpmEventsString': ( '', False ),  # PFW: extra MPM event XML.
               'cohesiveZoneRegions': ( [], False ),  # PFW: explicit CohesiveZoneRegions child XML.
               'mSubmitJobs': ( False, False ),  # PFW: submit generated batch job.
               'mWallTime': ( '00:30:00', False ),  # PFW: batch wall time.
               'needsNeighborList': ( None, True ),  # MPM: build particle neighbor list.
               'needsNodalNeighborList': ( None, True ),  # MPM: build nodal neighbor list.
               'neighborRadius': ( None, True ),  # MPM: SPH/contact neighbor radius.
               'nI': ( 5, False ),  # PFW: total cell count in x; non-periodic interior is nI-2.
               'nJ': ( 5, False ),  # PFW: total cell count in y; non-periodic interior is nJ-2.
               'nK': ( 5, False ),  # PFW: total cell count in z; non-periodic interior is nK-2.
               'normalAndPositionMethod': ( None, True ),  # MPM: surface normal/position method.
               'numSurfaceIntegrationPoints': ( None, True ),  # MPM: surface integration points per cohesive node.
               'objects': ( None, False ),  # PFW: geometric objects used to create particles.
               'outputType': ( 'vtk', False ),  # PFW: plot-file backend.
               'overlapCorrection': ( None, True ),  # MPM: overlap-correction mode.
               'overlapThreshold1': ( None, True ),  # MPM: first overlap-correction threshold.
               'overlapThreshold2': ( None, True ),  # MPM: second overlap-correction threshold.
               'overwriteExistingNormalsAndPositions': ( None, True ),  # MPM: overwrite supplied surface geometry.
               'parallelThreads': ( None, False ),  # PFW: writer-side parallel particle generation threads.
               'particleDataWriteInterval': ( None, True ),  # MPM: particle-data write interval.
               'particleFileFields': ( [], False ),  # PFW: particle columns to write.
               'particleRefinement': ( None, False ),  # PFW: particle refinement settings.
               'periodic': ( [ False, False, False ], False ),  # PFW: periodicity in x/y/z.
               'planeStrain': ( 0, True ),  # MPM: run in plane-strain mode.
               'plotGridFields': ( None, True ),  # MPM: write grid fields to plot output.
               'plotInterval': ( None, False ),  # PFW: output event interval.
               'plottableFields': ( None, True ),  # MPM: explicit particle-field output list.
               'plotUnscaledParticles': ( None, True ),  # MPM: plot particles without CPDI scaling.
               'ppc': ( 2, False ),  # PFW: particles per cell in all directions.
               'ppcx': ( None, False ),  # PFW: particles per cell in x.
               'ppcy': ( None, False ),  # PFW: particles per cell in y.
               'ppcz': ( None, False ),  # PFW: particles per cell in z.
               'prescribedBcTable': ( None, True ),  # MPM: enable time-dependent BC type table.
               'prescribedBoundaryFTable': ( None, True ),  # MPM: enable boundary deformation table.
               'prescribedBoundaryTransverseVelocities': ( [ [ 0.0, 0.0 ], [ 0.0, 0.0 ], [ 0.0, 0.0 ], [ 0.0, 0.0 ], [ 0.0, 0.0 ], [ 0.0, 0.0 ] ], True ),  # MPM: transverse velocities on each face.
               'prescribedFTable': ( None, True ),  # MPM: enable prescribed deformation-gradient table.
               'preventCZInterpenetration': ( None, True ),  # MPM: prevent cohesive-zone interpenetration.
               'profileCycleInterval': ( None, True ),  # MPM: profile-history cycle interval.
               'profileDirection': ( None, True ),  # MPM: profile-history direction.
               'profileHistory': ( None, True ),  # MPM: enable profile-history CSV output.
               'profileNumSlices': ( None, True ),  # MPM: number of profile-history slices.
               'profileVariables': ( None, True ),  # MPM: profile-history variables.
               'profileWriteInterval': ( None, True ),  # MPM: profile-history time interval.
               'reactionHistory': ( None, True ),  # MPM: enable boundary reaction history.
               'reactionWriteInterval': ( None, True ),  # MPM: reaction-history write interval.
               'resetDefGradForFullyDamagedParticles': ( None, True ),  # MPM: reset F for fully damaged particles.
               'resetDefGradForScaledSurfaceParticles': ( None, True ),  # MPM: reset F for CPDI-scaled surface particles.
               'restartCycleNum': ( 0, False ),  # PFW: restart cycle number.
               'restartInterval': ( None, False ),  # PFW: restart event interval.
               'restartJobDir': ( '.', False ),  # PFW: restart source directory.
               'runCheckTime': ( '00:02:00', False ),  # PFW: short check-run wall time.
               'runContinuation': ( False, False ),  # PFW: generate continuation run.
               'runDebug': ( False, False ),  # PFW: enable writer debug output.
               'separabilityMinDamage': ( 0.5, True ),  # MPM: damage threshold for field separability.
               'setDomainTemperature': ( None, True ),  # MPM: enable domain temperature table.
               'setDomainTemperatureRate': ( None, True ),  # MPM: enable domain temperature-rate table.
               'smallMass': ( None, True ),  # MPM: low-mass cutoff for nodes.
               'solverProfiling': ( None, True ),  # MPM: time solver subroutines.
               'sortObjects': ( False, False ),  # PFW: spatially sort geometry objects while writing particles.
               'stressControl': ( None, True ),  # MPM: enable stress-control driver.
               'stressControlAdaptiveSeek': ( None, True ),  # MPM: enable adaptive-seek normal stress-control driver.
               'stressControlResponseStrain': ( None, True ),  # MPM: strain interval for adaptive stress-error correction.
               'stressControlFilterStrain': ( None, True ),  # MPM: strain interval for stress filtering in adaptive control.
               'stressControlAdaptStrainWindow': ( None, True ),  # MPM: strain window for adaptive tangent updates.
               'stressControlAdaptGain': ( None, True ),  # MPM: normalized adaptive tangent update gain.
               'stressControlMaxRateRatio': ( None, True ),  # MPM: active stress-control rate cap relative to reference rate.
               'stressControlMaxFeedbackRateRatio': ( None, True ),  # MPM: feedback stress-control rate cap relative to reference rate.
               'stressControlSeekRateRatio': ( None, True ),  # MPM: bounded seek rate relative to reference rate.
               'stressControlMaxSeekRateRatio': ( None, True ),  # MPM: maximum bounded seek rate relative to reference rate.
               'stressControlMinStrainRate': ( None, True ),  # MPM: minimum reference strain rate for adaptive stress control.
               'stressControlMaxSeekStrain': ( None, True ),  # MPM: maximum accumulated seek strain before declaring target unreachable.
               'stressControlMaxSeekStrainIncrement': ( None, True ),  # MPM: maximum adaptive/seek strain increment per step.
               'stressControlCommandFilterStrain': ( None, True ),  # MPM: strain interval for smoothing adaptive stress-control commands.
               'stressControlMaxRateChangeRatio': ( None, True ),  # MPM: maximum per-step command rate change relative to reference strain rate.
               'stressControlJammingPressureRatio': ( None, True ),  # MPM: pressure fraction indicating load-path appearance in seek mode.
               'stressControlReengageTangentRatio': ( None, True ),  # MPM: tangent fraction used by adaptive seek re-engagement.
               'stressControlReengageRampStrain': ( None, True ),  # MPM: strain interval for blending seek back to active control.
               'stressControlWaveWarnRatio': ( None, True ),  # MPM: raw-filtered stress ratio warning threshold.
               'stressControlWaveCutbackRatio': ( None, True ),  # MPM: raw-filtered stress ratio that freezes re-engagement/adaptation.
               'stressControlStressFloor': ( None, True ),  # MPM: stress floor for adaptive stress-control ratios.
               'stressControlTangentFloorRatio': ( None, True ),  # MPM: learned tangent lower-bound ratio.
               'stressControlTangentCeilingRatio': ( None, True ),  # MPM: learned tangent upper-bound ratio.
               'stressControlMaxCouplingRatio': ( None, True ),  # MPM: learned off-diagonal normal tangent cap.
               'stressControlSolverDampingRatio': ( None, True ),  # MPM: damping ratio for active tangent solve.
               'stressControlKd': ( None, True ),  # MPM: stress-control derivative gain.
               'stressControlKi': ( None, True ),  # MPM: stress-control integral gain.
               'stressControlKp': ( None, True ),  # MPM: stress-control proportional gain.
               'stressTable': ( None, True ),  # MPM: time-dependent stress table.
               'stressTableInterpType': ( None, True ),  # MPM: interpolation type for stressTable.
               'subdivideParticles': ( None, True ),  # MPM: split particles spanning too much of a cell.
               'surfaceDetection': ( None, True ),  # MPM: automatic initial surface detection.
               'surfaceNormalAndPositionDamageThreshold': ( None, True ),  # MPM: damage threshold for disabling explicit surfaces.
               'surfaceQualityThreshold': ( None, True ),  # MPM: DFG alignment quality threshold.
               'surfaceTensionCoefficient': ( None, True ),  # MPM: surface-tension coefficient.
               'thinFeatureDFGThreshold': ( None, True ),  # MPM: thin-feature damage threshold.
               'timeIntegrationOption': ( None, True ),  # MPM: time-integration method.
               'totalBinderVolume': ( None, True ),  # MPM: total binder volume.
               'tracerCoordinates': ( None, True ),  # MPM: initial tracer coordinates.
               'tracerCycleInterval': ( None, True ),  # MPM: tracer-history cycle interval.
               'tracerHistory': ( None, True ),  # MPM: enable tracer-history CSV output.
               'tracerOutputPrefix': ( None, True ),  # MPM: tracer-history filename prefix.
               'tracerVariables': ( None, True ),  # MPM: tracer-history variables.
               'tracerWriteInterval': ( None, True ),  # MPM: tracer-history time interval.
               'treatFullyDamagedAsSingleField': ( None, True ),  # MPM: merge fully damaged fields.
               'updateMethod': ( None, True ),  # MPM: particle/grid update method.
               'updateOrder': ( None, True ),  # MPM: update order for XPIC/FMPM.
               'useCrackTipDetection': ( None, True ),  # MPM: enable crack-tip detection.
               'useEvents': ( None, True ),  # MPM: enable MPM event manager actions.
               'useInternalForceAsFaceReaction': ( None, True ),  # MPM: use internal force for face reactions.
               'useNodePosForArea': ( None, True ),  # MPM: use node positions for nodal areas.
               'usePhysicsScaling': ( None, True ),  # MPM: enable physics scaling of linear systems.
               'useReferenceVectorsForParticleUpdate': ( None, True ),  # MPM: use reference vectors in particle updates.
               'useSinusoidalDamageField': ( False, False ),  # PFW: initialize sinusoidal damage field.
               'useSurfacePositionForContact': ( None, True ),  # MPM: use particle surface positions for contact.
               'wavyCrack': ( False, False ),  # PFW: initialize wavy-crack geometry/damage.
               'writeLinearSystem': ( None, True ),  # MPM: write linear system data.
               'writeParticleData': ( None, True ),  # MPM: write particle data files.
               'writeStatistics': ( None, True ),  # MPM: write solver statistics CSV.
               'xmax': ( 0.5, False ),  # PFW: physical-domain maximum x.
               'xmin': ( -0.5, False ),  # PFW: physical-domain minimum x.
               'xpar': ( 1, False ),  # PFW: partition count in x.
               'ymax': ( 1.0, False ),  # PFW: physical-domain maximum y.
               'ymin': ( 0.0, False ),  # PFW: physical-domain minimum y.
               'ypar': ( 1, False ),  # PFW: partition count in y.
               'zmax': ( 0.5, False ),  # PFW: physical-domain maximum z.
               'zmin': ( -0.5, False ),  # PFW: physical-domain minimum z.
               'zpar': ( 1, False ),  # PFW: partition count in z.
             }

# This must correspond to the order in which fields are written in the particle file below
particleFieldOrder=["Velocity",
                    "MaterialType",
                    "ContactGroup",
                    "SurfaceFlag",
                    "Damage",
                    "Porosity",
                    "Temperature",
                    "StrengthScale",
                    "CZTag",
                    "RVector",
                    "MaterialDirection",
                    "SurfaceNormal",
                    "SurfacePosition",
                    "SurfaceTraction",
                    "ShrinkageFlag"]

# New dictionary input approach.  Inputs are expected to use current PFW keys
# directly.  Use pfw_inputFixer.py on obsolete inputs before running this writer.
pfw = job.pfw if hasattr(job, 'pfw') else {}
if not isinstance(pfw, dict):
  raise TypeError('The input file must define pfw as a dictionary')

unknownPfwKeys = sorted(key for key in pfw if key not in parameters)
if unknownPfwKeys:
  raise KeyError(
    'Unknown pfw key(s): ' + ', '.join(unknownPfwKeys) +
    '. Update the pfw_input file or run pfw_inputFixer.py to create a .fixed version.'
  )

tabIndent = 3*"  "
parameterStrings = []
for paramName, paramTuple in parameters.items():
  # Check if param is passed from input script, if not assign default value.
  paramValue = pfw[paramName] if paramName in pfw else paramTuple[0]

  # Add solver XML attributes only for parameters marked as solver attributes.
  if paramValue != None and paramTuple[1]:
    parameterStrings.append(tabIndent + paramName + '="' + str(paramValue).replace('[','{').replace(']','}').replace("'","") + '"' + '\n')

  # Add global variable to be used by particle file writer.
  globals()[paramName] = paramValue

if dependencies is None:
  dependencies = []
elif isinstance(dependencies, tuple):
  dependencies = list(dependencies)
elif not isinstance(dependencies, list):
  raise TypeError('pfw["dependencies"] must be a list or tuple of staged dependency names')
for sourcePath, destinationPath in dependencyCopies:
  dep = str(destinationPath)
  if dep not in dependencies:
    dependencies.append(dep)
pfw["dependencies"] = dependencies
globals()["dependencies"] = dependencies
print("Dependency files: ", dependencies)

jobName = caseName if caseName else inputFile.replace('pfw_input_', '')

def _truthy_pfw_flag(value):
  if value is None or value is False or value == 0:
    return False
  if isinstance(value, str) and value.strip().lower() in ('', '0', 'false', 'none', 'off', 'no'):
    return False
  return True

# Explicit contact and cohesive-zone inputs require matching particle fields.
requiresSurfaceContactFields = (
  _truthy_pfw_flag(pfw.get('explicitSurfaceNormalInfluence')) or
  _truthy_pfw_flag(pfw.get('useSurfacePositionForContact')) or
  ('mpmEventsString' in pfw and 'CohesiveZone' in str(pfw['mpmEventsString']))
)
if requiresSurfaceContactFields:
  missingFields = [f for f in ('SurfaceNormal', 'SurfacePosition') if f not in particleFileFields]
  if missingFields:
    raise ValueError(
      'Explicit contact or cohesive-zone events require particleFileFields to include: ' +
      ', '.join(missingFields)
    )

# Remove new line from last parameter to be added (for XML formatting).

if parameterStrings:
  parameterStrings[-1] = parameterStrings[-1].replace('\n','')
mpmSolverParameterString = ''.join(parameterStrings)

cohesiveZoneRegionString = ""

# Remove fields form particleFileOrder the user does not wish to write to particle field (particleFieldOrder preseveres the correct header order for values written to the particle file)
particleFileFields.extend([ 'RVector' ]) # MaterialType, velocity, contact group, and surface flags should all default to 0 if unspecified in GEOS initialization
particleFileFields = set(particleFileFields)
particleFieldOrder = [ f for f in particleFieldOrder if f in particleFileFields ]

# Interior Domain
# The GEOS input xml file specifies and xmin,xmax, ni, etc. based on the total domain
# size (with ghost cells).  The user inputs in the python input file will be physical
# domain size (interior only) and actual number of grid cells, to make partitioning
# easier.  here we calculate the true domain extents and particle sizes.
# Discretization
NI = nI   # total grid cells in the x-direction (counting ghosts)
NJ = nJ   # total grid cells in the y-direction (counting ghosts)
NK = nK   # total grid cells in the z-direction (counting ghosts)
ppcx = ppcx if ppcx != None else ppc
ppcy = ppcy if ppcy != None else ppc
ppcz = ppcz if ppcz != None else ppc

# list of geometry creation objects
# if objects == None:
#   objects = job.make_objects()

# Batch parameters for GEOS runs.  An error will result if there are too many cores for
 
# TO DO -- add code for parallel file generation to only construct pfw objects in rank particle slice
# # User can specify a list of objects or a function that generates objects
# # the latter is prefered if objects are slow to generate (like those requiring
# # voronoi tesselations.  If there are a large number of objects, like for granular
# # systems, it is useful for each rank to only generate the objects it will contain.
# # For this, the user can define a job.make_objects(rankxmin,rankxmax) based on
# # x slices.  TODO: make objects have a construct() method that can be called by
# # pfw, so the list of objects can be generated cheaply and the user doesn't have
# # to worry about rank slicing.
if ('objects' in pfw):
  objects = pfw["objects"]
elif ( hasattr(job, 'make_objects') ):
  # list of geometry creation objects
  from inspect import signature
  if str(signature(job.make_objects)) == '()':
    # Old version, all ranks construct all objects:
    objects = job.make_objects()
  else:
    # This will be used to make objects only be created if their bounding box contains the current
    # ranks slice.
    rankxmin = xmin + (rank/num_ranks)*(xmax-xmin)
    rankxmax = xmin + ( (rank+1)/num_ranks)*(xmax-xmin)
    objects = job.make_objects(rankxmin,rankxmax)
else:
  # Throw error if no objects defined.  you can still specify objects=[] to run with no objects.
  # but this will error if no objects or make objects function exists in input file.
  print( "You don't have any objects" )
  
# Batch parameters for GEOSX runs.  An error will result if there are too many cores for

# a low resolution simulation.  If there is insufficient run-time to obtain a signal
# for a given run, that run will have its results ommited from the Hugoniot analysis.
mPartition = mPartition if not runDebug else "pdebug" 

# mCores is set by number of partitions in each direction, this doesn't need to be
# an additional input.
mCores = int(xpar*ypar*zpar)

# We used to set this manually, but ranksPerNode changes with each machine.
# This will ensure consistency since we now have that value for each platform.
mNodes= int(np.ceil(float(mCores)/float(ranksPerNode)))
if rank == 0:
  print('machine = ',machine,', mNodes = ',mNodes,', mCores = ',mCores,', coresPerNode = ',coresPerNode, ', ranksPerNode = ', ranksPerNode)

if mBank == None:
  # Get default bank from userdefs
  username = getpass.getuser()
  userDefsFile = str('userDefs_'+str(username))
  userDefs = importlib.import_module(userDefsFile)
  mBank = userDefs.defaultBank

[wH,wM,wS]=mWallTime.split(":")
mWallTimeMinutes=int(wH)*60+int(wM)
if mWallTimeMinutes > 60 and runDebug:
  print("Wall time of debug job exceeded 60 minutes and was reset")
  mWallTimeMinutes = 60
  mWallTime="01:00:00"

maxRestartTime = mWallTimeMinutes*60 - min(mWallTimeMinutes, lastRestartBufferInSeconds)

coreHours = float(int(mCores))*(float(int(wH))+float(int(wM))/60.+float(int(wS))/3600.)
cpuTimeCost = (23295./2000000.)*coreHours
if rank == 0:
  print('Approximate LC bank time cost for this simulation is $',cpuTimeCost,'.')

# Material array
if materials == None:
  # Throw error
  print( "A materials array must be specified in the input file!" )
  comm.Abort()

matsOrig = materials
numMats = len(matsOrig)
mats = str(matsOrig).replace("[",'"{')
mats = mats.replace("]",'}"')
mats = mats.replace("'","")

# Gather list of subregions from geometry objects (each subregion constitutes a unique material and particleType ID, regions hold subregions of the same material type)
subregions_all = []
for obj in objects:
  subregions = obj.getSubregions()
  subregions_all.extend(subregions)

particleTypesPerMat = [set() for m in materials]
for s in subregions_all:
  particleTypesPerMat[s[0]].add(s[1])

numSubRegions = 0
for s in particleTypesPerMat:
  numSubRegions += len(s)
if rank == 0:
  print("Num subregions:", numSubRegions)

particleRefinement = particleRefinement if particleRefinement != None else [ 1 for i in range(numMats) ]  # Create list of size materials all ones


# ============================================================================================
# ERROR Checking
# ============================================================================================


if rank == 0:
  no_errors = True

  if ( planeStrain == 1 and NK != 3):
    print('nK should = 3 for plane Strain!!')
    no_errors = False

  if ( planeStrain == 1 and zpar != 1):
    print('zpar should = 1 for plane Strain!!')
    no_errors = False

  if not no_errors:
    if not flux:
      comm.Abort()
    else:
      sys.exit()


# ============================================================================================
# CREATE PARTICLE FILE
# ============================================================================================


timer = time.time()
particleFileName = 'mpmParticleFile_'+inputFile.replace('pfw_input_',"")

# interior discretizatiom
nI = NI if periodic[0] else NI-2   # interior grid cells in the x-direction
nJ = NJ if periodic[1] else NJ-2   # interior grid cells in the y-direction
nK = NK-2 if planeStrain == 1 or not periodic[2] else NK   # interior grid cells in the z-direction

# grid cell spacing
dX = (xmax - xmin)/nI
dY = (ymax - ymin)/nJ
dZ = (zmax - zmin)/nK

# total domain dimensions (counting ghosts)
XMIN = xmin if periodic[0] else xmin - dX 
XMAX = xmax if periodic[0] else xmax + dX
YMIN = ymin if periodic[1] else ymin - dY
YMAX = ymax if periodic[1] else ymax + dY
ZMIN = zmin - dZ if planeStrain == 1 or not periodic[2] else zmin
ZMAX = zmax + dZ if planeStrain == 1 or not periodic[2] else zmax

# particles in each direction
ni = ppcx*nI
nj = ppcy*nJ
nk = 1 if planeStrain == 1 else ppcz*nK

# particle dimensions
dx = dX/ppcx
dy = dY/ppcy
dz = dZ if planeStrain == 1 else dZ/ppcz

# Sum particle volume to compute volume fraction.
particleVolume = 0.
domainVolume = ( pfw["xmax"] - pfw["xmin"] )*( pfw["ymax"] - pfw["ymin"] )*( pfw["zmax"] - pfw["zmin"] ) 

generateParticleFile = generateParticleFile if not runContinuation else False
if generateParticleFile:
  print('Writing particle file' + ("" if num_ranks == 1 else f" on rank {rank}" ) + '...')

  # Delimiter for particle file
  delim = '\t'

  rank_particleFileName = particleFileName + '_' + str(rank)
  particleFile = open(rank_particleFileName, 'w')

  if planeStrain == 1:
    surfaceDepth = 1.2*np.sqrt(dX*dX + dY*dY) / min(ppcx, ppcy) #np.sqrt(dX*dX + dY*dY) / min(ppcx, ppcy)
  else:
    surfaceDepth = np.sqrt(dX*dX + dY*dY + dZ*dZ) / min(ppcx, min( ppcy, ppcz))

  # list of i,j,k indices at the center of each partition.
  ipc=np.empty(xpar,dtype=int)
  jpc=np.empty(ypar,dtype=int)
  kpc=np.empty(zpar,dtype=int)
  for p in range(xpar):
    ipc[p] = np.ceil( (p+0.5)*ppcx*NI/xpar ) - ppcx
  for p in range(ypar):
    jpc[p] = np.ceil( (p+0.5)*ppcy*NJ/ypar ) - ppcy
  for p in range(zpar):
    if planeStrain == 1:
      kpc[p] = 1
    else:
      kpc[p] = np.ceil( (p+0.5)*ppcz*NK/zpar ) - ppcz

  if rank == 0:
    print('xpar = ',xpar,', ppcx*NI = ',ppcx*NI,', partition centers at i = ',ipc)
    print('ypar = ',ypar,', ppcy*NJ = ',ppcy*NJ,', partition centers at j = ',jpc)
    print('zpar = ',zpar,', ppcz*NK = ',ppcz*NK,', partition centers at k = ',kpc)

    # loop through domain and fill particles.

    print("ni =",ni,", nj =",nj,", nk =",nk)

  # Make sure no errors are detected on rank 0 before proceeding with particle generation
  if not flux:
    comm.Barrier()

  max_num_particles = ni*nj*nk
  
  n_p = 0
  for i in range(1+math.ceil(ni*rank/num_ranks), math.ceil(ni*(rank+1)/num_ranks)+1):
    print('creating files, row',i,'/',ni,', estimated time remaining = ',(ni-i)/i*(time.time()-timer),'s')
    x = xmin + (i - 0.5)*dx

    if(sortObjects):
      sliceObjects = [ob for ob in objects if (ob.xMin() <= x and ob.xMax() >= x)]
    else:
      sliceObjects = objects

    for j in range(1,nj+1):
        y = ymin + (j - 0.5)*dy
        for k in range(1,nk+1):
          z = zmin + (k - 0.5)*dz

          match = False
          ob = 0

          while (ob < len(sliceObjects) and match == False):
            object = sliceObjects[ob]
            ob = ob+1
            pt = np.array([x,y,z])
            voxelFlag = object.isInterior( pt, surfaceDepth ) # Voxel flags greater than or equal to 0 denote interior regions of object
            if( voxelFlag >= 0 ):
              match = True

              # Get the particle type, default is CPDI
              if hasattr(object, 'getParticleType'):
                particleType = object.getParticleType( pt )
              else:
                particleType = object.particleType( object, pt ) if callable( object.particleType ) else object.particleType

              # set the particle damage to be the object damage unless
              # overwritten by surface flags.
              if "Velocity" in particleFileFields:
                if hasattr(object, 'getVelocity'):
                  velocity = object.getVelocity( pt )
                else:
                  velocity = object.vel( object, pt ) if callable( object.vel ) else object.vel

              if "Damage" in particleFileFields:
                # set the particle damage to be the object damage unless
                # overwritten by surface flags.
                if hasattr(object, 'getDamage' ): # some internal function defines spatially varing initial damage
                  damage = object.getDamage( pt )
                else: # damage is constant for the object:
                  damage = object.damage(object, pt ) if callable( object.damage ) else object.damage

                # force damage to be a scalar value.
                if(useSinusoidalDamageField):
                  damage = 0.5*( np.sin( 2.0*np.pi*(x-xmin)/(xmax-xmin) )*np.sin(  3.0*np.pi*(y-ymin)/(ymax-ymin) ) + 1 )

                if(wavyCrack):
                  h = 2*dy
                  val = 0.25 * (ymax - ymin) * np.cos(2.0*3.1415926535*(x-xmin)/(xmax-xmin)) + ymin + 0.5 * (ymax - ymin)
                  if( val - h < y and y < val + h ):
                    damage = 1
                  else:
                    damage = 0

              if "Porosity" in particleFileFields:
                if hasattr(object, 'getPorosity' ):
                  porosity = object.getPorosity( pt )
                else: # damage is constant for the object:
                  porosity = object.porosity(object, pt ) if callable( object.porosity ) else object.porosity

              if "Temperature" in particleFileFields:
                if hasattr(object, 'getTemperature' ):
                  temperature = object.getTemperature( pt )
                else: # temperature is constant for the object:
                  temperature = object.temperature(object, pt ) if callable( object.temperature ) else object.temperature

              # Particle Surface Flags:
              #  enum struct SurfaceFlag : integer
              #  {
              #    0: Interior,
              #    1: FullyDamaged,
              #    2: Surface,
              #    3: Cohesive   
              #    4: Damaged Cohesive 
              #  };

              surfaceFlag = voxelFlag

              surfacePosition = np.array([0.0, 0.0, 0.0])
              if "SurfacePosition" in particleFileFields and surfaceFlag != 0:
                 surfacePosition = object.getSurfacePosition( pt )
                
              surfaceNormal = np.array([0.0, 0.0, 0.0])
              if "SurfaceNormal" in particleFileFields and surfaceFlag != 0:
                surfaceNormal = np.array(object.getSurfaceNormal( pt ))
                
                if (np.linalg.norm(surfaceNormal) < 0.0001 ):
                  print("Near zero surface normal specfied for surface flagged particle.")

              surfaceTraction = np.array([0.0,0.0,0.0])  
              if "SurfaceTraction" in particleFileFields and surfaceFlag != 0:
                if hasattr(object, 'getSurfaceTraction'):
                  surfaceTraction = object.getSurfaceTraction( pt )
                else:
                  surfaceTraction = object.surfaceTraction(object, pt) if callable(object.surfaceTraction) else object.surfaceTraction

              if "MaterialType" in particleFileFields:
                if hasattr(object, 'getMat'):
                  mat = int( object.getMat( pt ) )
                else:
                  mat = int( object.mat(object, pt) if callable(object.mat) else object.mat )

              if "ContactGroup" in particleFileFields:
                if hasattr(object,'getGroup'):
                    group = object.getGroup( pt )
                else:
                    if hasattr(object, 'group'):
                      group = object.group
                    else:
                      group = 0

              if "MaterialDirection" in particleFileFields:
                # material direction, These will be read from object, will default to [1,0,0] if not 
                # specified.
                if hasattr( object, 'getMatDir' ):
                  matDir = object.getMatDir( pt )
                else:
                  if hasattr( object, 'matDir' ):
                    matDir = object.matDir( object, matDir ) if callable( object.matDir ) else object.matDir
                  else:
                    matDir = np.array([[1.0, 0.0, 0.0],[0.0, 1.0, 0.0],[0.0, 0.0, 1.0]])
  
              if "StrengthScale" in particleFileFields:
                # object may have some constant or spatially varying strength scale.
                # which is used by some material properties to modify strength.
                # this is an alternative to using internal weibull scaling, but may
                # be useful for defining other spatial distributions or object
                # specific weak layers, etc. defaults to 1 if not specified.   
                if hasattr(object,'getStrengthScale'):
                    strengthScale = object.getStrengthScale( pt )
                else:
                    if hasattr(object, 'strengthScale'):
                      strengthScale = object.strengthScale( object, pt ) if callable(object.strengthScale) else object.strengthScale
                    else:
                      strengthScale = 1.0
              
              czTag = 0
              if "CZTag" in particleFileFields:
                if hasattr(object,'getCZTag'):
                    czTag = object.getCZTag( pt )
                else:
                    if hasattr(object, 'getCZTag'):
                      czTag = object.getCZTag( object, pt ) if callable(object.getCZTag) else object.getCZTag
                    else:
                      czTag = 0

              # Check for fields with None values
              # Get the particle type, default is CPDI
              if particleType == None:
                print("ParticleType value from", object.name,"was None!")
                sys.exit(0)

              if "Velocity" in particleFileFields and all(v is None for v in velocity):
                print("Velocity value from", object.name,"was None!")
                sys.exit(0)

              if "Damage" in particleFileFields and damage == None:
                print("Damage value from", object.name,"was None!")
                sys.exit(0)

              if "Porosity" in particleFileFields and porosity == None:
                print("Porosity value from", object.name,"was None!")
                sys.exit(0)

              if "Temperature" in particleFileFields and temperature == None:
                print("Temperature value from", object.name,"was None!")
                sys.exit(0)

              if "SurfaceFlag" in particleFileFields and surfaceFlag == None:
                print("SurfaceFlag value from", object.name,"was None!")
                sys.exit(0)

              if "SurfacePosition" in particleFileFields and surfaceFlag != 0 and all(v is None for v in surfacePosition):
                print("SurfacePosition value from", object.name,"was None!")
                sys.exit(0)

              if "SurfaceNormal" in particleFileFields and surfaceFlag != 0 and all(v is None for v in surfaceNormal):
                print("SurfaceNormal value from", object.name,"was None!")
                sys.exit(0)

              if "SurfaceTraction" in particleFileFields and surfaceFlag != 0 and all(v is None for v in surfaceTraction):
                print("SurfaceTraction value from", object.name,"was None!")
                sys.exit(0)

              if "MaterialType" in particleFileFields and mat == None:
                print("MaterialType value from", object.name,"was None!")
                sys.exit(0)

              if "ContactGroup" in particleFileFields and group == None:
                print("ContactGroup value from", object.name,"was None!")
                sys.exit(0)

              if "MaterialDirection" in particleFileFields and all(v is None for v in matDir):
                print("MaterialDirection value from", object.name,"was None!")
                sys.exit(0)
  
              if "StrengthScale" in particleFileFields and strengthScale == None:
                print("Strengthscale value from", object.name,"was None!")
                sys.exit(0)

              if "CZTag" in particleFileFields and czTag == None:
                print("CZTag value from", object.name, "was None!")
                sys.exit(0)

              # particleTypesPerMat[mat].add( particleType )

              dxr = dx/particleRefinement[mat]
              dyr = dy/particleRefinement[mat]
              dzr = dz if planeStrain == 1 else dz/particleRefinement[mat]
              
              for ri in range(particleRefinement[mat]):
                for rj in range(particleRefinement[mat]):
                  for rk in range( ( 1 if planeStrain == 1 else particleRefinement[mat] ) ):
                    xr = x - 0.5*dx + (ri + 0.5)*dxr
                    yr = y - 0.5*dy + (rj + 0.5)*dyr
                    zr = z - 0.5*dz + (rk + 0.5)*dzr
                    
                    # only create particle if mat>=0, that way we can specify mat=-1 to generate a 
                    # defect or void.
                    if(mat>=0):
                      n_p = n_p + 1

                      particleVolume += dxr*dyr*dzr

                      pString = str(n_p) + delim \
                                + str(xr) + delim \
                                + str(yr) + delim \
                                + str(zr) + delim \
                                + str(particleType)

                      if "Velocity" in particleFileFields:
                        pString = pString + delim + str(velocity[0]) + delim \
                                                  + str(velocity[1]) + delim \
                                                  + str(0.0 if planeStrain == 1 else velocity[2])

                      if "MaterialType" in particleFileFields:
                        pString = pString + delim + str(mat)
                        
                      if "ContactGroup" in particleFileFields:
                        pString = pString + delim + str(group)

                      if "SurfaceFlag" in particleFileFields:
                        pString = pString + delim + str(surfaceFlag)

                      if "Damage" in particleFileFields:
                        pString = pString + delim + str(damage)

                      if "Porosity" in particleFileFields:
                        pString = pString + delim + str(porosity)

                      if "Temperature" in particleFileFields:
                        pString = pString + delim + str(temperature)

                      if "StrengthScale" in particleFileFields:
                        pString = pString + delim + str(strengthScale)

                      if "CZTag" in particleFileFields:
                        pString = pString + delim + str(czTag)

                      if "RVector" in particleFileFields:
                        pString = pString + delim + str(dxr*0.5) + delim \
                                                  + str(0) + delim \
                                                  + str(0) + delim \
                                                  + str(0) + delim \
                                                  + str(dyr*0.5) + delim \
                                                  + str(0) + delim \
                                                  + str(0) + delim \
                                                  + str(0) + delim \
                                                  + str(dzr*0.5)

                      if "MaterialDirection" in particleFileFields:
                        if (np.array(matDir).size == 9):
                          pString = pString + delim + str(matDir[0][0]) + delim \
                                                    + str(matDir[0][1]) + delim \
                                                    + str(matDir[0][2]) + delim \
                                                    + str(matDir[1][0]) + delim \
                                                    + str(matDir[1][1]) + delim \
                                                    + str(matDir[1][2]) + delim \
                                                    + str(matDir[2][0]) + delim \
                                                    + str(matDir[2][1]) + delim \
                                                    + str(matDir[2][2])
                        elif (np.array(matDir).size == 3):  # fill the 2nd and 3rd row with nonsense since unspecified.  BEWARE!!!
                          pString = pString + delim + str(matDir[0]) + delim \
                                                    + str(matDir[1]) + delim \
                                                    + str(matDir[2]) + delim + "0" + delim + "1" + delim + "0" + delim + "0" + delim + "0" + delim + "1"
                        else:
                          print("matDir isn't the size 3 or 3x3")

                      if "SurfaceNormal" in particleFileFields:
                        if ( planeStrain == 1 and surfaceNormal[2] != 0.0 ):
                          # enforce plane strain and renormalize:
                          norm = float( np.sqrt( surfaceNormal[0]*surfaceNormal[0] + surfaceNormal[1]*surfaceNormal[1] ) )
                          pString = pString + delim + str(surfaceNormal[0]/norm) + delim \
                                            + str(surfaceNormal[1]/norm) + delim \
                                            + str(0.0)                     
                        else:
                          # assume normal is alread unit vector:
                          pString = pString + delim + str(surfaceNormal[0]) + delim \
                                                  + str(surfaceNormal[1]) + delim \
                                            + str(surfaceNormal[2]) 
                      
                      if "SurfacePosition" in particleFileFields:
                        pString = pString + delim + str(surfacePosition[0]) + delim \
                                                  + str(surfacePosition[1]) + delim \
                                                  + str(0.0 if planeStrain == 1 else surfacePosition[2])

                      if "SurfaceTraction" in particleFileFields:
                        pString = pString + delim + str(surfaceTraction[0]) + delim \
                                                  + str(surfaceTraction[1]) + delim \
                                                  + str(0.0 if planeStrain == 1 else surfaceTraction[2])

                      if "ShrinkageFlag" in particleFileFields:
                        pString = pString + delim + str( object.flag if hasattr( object, 'flag') else 0)

                      pString = pString +'\n'
                      particleFile.write(pString)

  particleFile.close()

  # Wait for all mpi processes to finish generating particles
  if flux:
    print('PFW does not support MPI on flux currently')
  else:
    comm.Barrier()

  n_p = 0
  if rank == 0:
    # Merge each process's particle files together
    # TODO: may be faster to use linux command
    with open(particleFileName, 'w') as outfile:
      # Write column headers
      columnNames = "ID" + delim + "PositionX" + delim + "PositionY" + delim + "PositionZ" + delim + "ParticleType"
      for field in particleFieldOrder:
        fieldString = field

        if field == "Velocity" or field == "SurfaceNormal" or field == "SurfacePosition" or field == "SurfaceTraction":
          fieldString = field + "X" + delim + field + "Y" + delim + field + "Z"

        if field == "RVector" or field == "MaterialDirection":
          fieldString =  field + "XX" + delim + \
                         field + "XY" + delim + \
                         field + "XZ" + delim + \
                         field + "YX" + delim + \
                         field + "YY" + delim + \
                         field + "YZ" + delim + \
                         field + "ZX" + delim + \
                         field + "ZY" + delim + \
                         field + "ZZ"

        columnNames = columnNames + delim + fieldString

      columnNames = columnNames + "\n"
      outfile.write(columnNames)

      for r in range(0,num_ranks):
        with open(particleFileName + '_'  +str(r)) as infile:
          for line in infile:
            n_p = n_p + 1
            # replace the per-rank id with an ordered global particle id:
            outfile.write(str(n_p) + ' ' + line.split(delim, 1)[1])
        subprocess.call(["rm",particleFileName+'_'+str(r)],cwd=PWD)

    print('Created n_p =',n_p,' particles in t = ',time.time()-timer)
    print('Particle volume =',particleVolume,', Domain volume = ',domainVolume )
    print('Particle volume fraction =', particleVolume/domainVolume )
    print('Average number of particles per rank =', n_p/mCores)
else:
  print('Skipping particle file generation...')

# ===========================================
# CONTINUATION OF PREVIOUS JOB
# ===========================================

restartStr = ''
if runContinuation:
  restart_job_dir = job.pfw["restartJobDir"]
  restart_cycle_num = job.pfw["restartCycleNum"]

  assert os.path.isdir(restart_job_dir), "Could not find job directory with name:" + restart_job_dir

  path = pathlib.Path(restart_job_dir)
  # runLocation = path.parent
  jobName = path.name

  restart_file = 'mpm_' + jobName + '_restart_' + '{:09d}'.format(restart_cycle_num)

  restartStr = '-r ' + restart_file 

  shutil.copytree(os.path.join(path, restart_file), restart_file)
  shutil.copy(os.path.join(path, restart_file + '.root'),  '.')

  # Copy particle file and rename even though it will no tbe used since we are reading from restart file
  shutil.copy(os.path.join(path, 'mpmParticleFile_' + jobName), particleFileName )

# Select between VTK and Silo output. Extra Silo grid fields may be requested
# with pfw["gridFieldNames"], pfw["siloGridFieldNames"], or pfw["siloGridFields"].
siloGridFieldNamesForOutput = _resolve_pfw_silo_grid_field_names(pfw)
siloGridFieldNamesAttribute = ""
if siloGridFieldNamesForOutput:
  if outputType != 'silo':
    raise ValueError('PFW Silo grid-field keys are only valid when pfw["outputType"] == "silo"')
  siloGridFieldNamesAttribute = f'\n    gridFieldNames="{_format_geos_name_array(siloGridFieldNamesForOutput)}"'

if outputType == 'vtk':
  periodicEventOutputString = 'vtkOutput'
  outputBlockOutputString="""<VTK
    name="vtkOutput"
    format="ascii"/>"""
elif outputType == 'silo':
  if parallelThreads is None:
    parallelThreads = min( mCores , coresPerNode )
  periodicEventOutputString = 'siloOutput'
  outputBlockOutputString=f"""<Silo
    name="siloOutput"
    plotFileRoot="mpm_cpdi"
    plotLevel="1"
    parallelThreads="{parallelThreads}"
    writeCellElementMesh="1"
    writeFaceElementMesh="0"
    writeEdgeMesh="0"
    writeFEMFaces="0"{siloGridFieldNamesAttribute}/>"""
else:
  raise ValueError('pfw["outputType"] must be either "vtk" or "silo"')

# ===========================================
# CREATE INPUT FILE

# ===========================================

# # Gather particleTypesPerMat from each process
# recv_particleTypesPerMat = None
# for r in range(1,num_ranks):
#   for m in range(numMats):
#     if rank == r:
#       comm.send(particleTypesPerMat[m], dest=0, tag=11)
#       # print("Rank 0 sent data: ", particleTypesPerMat[m])
#     elif rank == 0:
#       data = comm.recv(source=r, tag=11)
#       for d in data:
#         particleTypesPerMat[m].add(d)
#       # print("Rank", r, "received data: ", data)

if rank == 0:
  print('Writing input file...')

  particleBlockString=""
  particleTypeString=""
  particleRegionString=""
  targetRegionsString=""
  blockIndex = 0
  for i in range(numMats):
    numTypes = len(particleTypesPerMat[i])
    types = list(particleTypesPerMat[i])
    regionBlocksStr = ""
    for j in range(numTypes):
      regionBlocksStr += "pb"+str(blockIndex)
      
      if types[j] == 0: # Single point
        particleTypeString+="SinglePoint"
      if types[j] == 1: # Single point with B-splines
        particleTypeString+="SinglePointBSpline"
      if types[j] == 2: # CPDI
        particleTypeString+="CPDI"
      if types[j] == 3: #CPTI
        particleTypeString+="CPTI"
      if types[j] == 4: #CPDI2
        particleTypeString+="CPDI2"
      if types[j] < 0 or types[j] > 4:
        print("Unknown particle type!")
        sys.exit(0)
      
      if j < numTypes - 1:
        regionBlocksStr+=", "
      if blockIndex < numSubRegions - 1:
        particleTypeString+=", "

      blockIndex += 1
    
    particleBlockString += regionBlocksStr
    targetRegionsString += "particles/ParticleRegion"+str(i+1)
    if i < numMats-1:
      particleBlockString+=", "
      targetRegionsString+=", "
    particleRegionString+=f"""
    <ParticleRegion
        name="ParticleRegion{i+1}"
        meshBody="particles"
        particleBlocks="{{ {regionBlocksStr} }}"
        materialList="{{ {matsOrig[i]} }}"/>"""


  # Format explicit solver child XML blocks after defaults have been resolved.
  # Legacy event/material migrations belong in pfw_inputFixer.py, not here.
  cohesiveZoneRegionString = _format_solver_child_xml_block(
    "CohesiveZoneRegions",
    cohesiveZoneRegions
  )
  mpmEventsBlock = _format_solver_child_xml_block(
    "MPMEvents",
    mpmEventsString
  )
  geosInputFileName = 'mpm_'+inputFile.replace('pfw_input_',"")+'.xml'

  geosInputFile = open(geosInputFileName, 'w')

  geosInputFileString = f"""<?xml version="1.0" ?>
<!-- 
srun -n {mCores:d} {geosPath} -i {geosInputFileName}
-->
<Problem>

  <Mesh>
    <InternalMesh
      name="backgroundGrid"
      elementTypes="{{ C3D8 }}"
      xCoords="{{ {XMIN}, {XMAX} }}"
      yCoords="{{ {YMIN}, {YMAX} }}"
      zCoords="{{ {ZMIN}, {ZMAX} }}"
      nx="{{ {NI} }}"
      ny="{{ {NJ} }}"
      nz="{{ {NK} }}"
      periodic="{{ {int(periodic[0])}, {int(periodic[1])}, {int(False if planeStrain == 1 else periodic[2])} }}"
      cellBlockNames="{{ cb1 }}"/>
      
    <ParticleMesh
      name="particles"
      particleFile="{particleFileName}"
      particleBlockNames="{{ {particleBlockString} }}"
      particleTypes="{{ {particleTypeString} }}"/>
  </Mesh>

  <ElementRegions>
    <CellElementRegion
      name="CellRegion1"
      meshBody="backgroundGrid"
      cellBlocks="{{ cb1 }}"
      materialList="{{ null }}"/>
  </ElementRegions>

  <ParticleRegions>{particleRegionString}
  </ParticleRegions>

  <Solvers
    gravityVector="{{ 0.0, 0.0, 0.0 }}">
    <SolidMechanics_MPM
      name="mpmsolve"
      discretization="FE1"
      targetRegions="{{ backgroundGrid/CellRegion1, {targetRegionsString} }}"
{mpmSolverParameterString}>{cohesiveZoneRegionString}{mpmEventsBlock}
    </SolidMechanics_MPM>
  </Solvers>

  <Constitutive>
    <ElasticIsotropic
      name="null"
      defaultDensity="1000"
      defaultBulkModulus="1.0e9"
      defaultShearModulus="1.0e9"/>
{materialPropertyString}
  </Constitutive>

  <Events
    maxTime="{endTime}">
    <PeriodicEvent
      name="solverApplications"
      target="/Solvers/mpmsolve"/>
    <PeriodicEvent
      name="outputs"
      timeFrequency="{plotInterval}"
      target="/Outputs/{periodicEventOutputString}"/>
    <PeriodicEvent
      name="restart"
      timeFrequency="{restartInterval}"
      target="/Outputs/restartOutput"/> 
    <HaltEvent
      maxRuntime="{maxRestartTime}"/>
  </Events>

  <NumericalMethods>
    <FiniteElements>
      <FiniteElementSpace
        name="FE1"
        order="1"/>
    </FiniteElements>
  </NumericalMethods>

  <Outputs>
    {outputBlockOutputString}
    <Restart
      name="restartOutput"/>
  </Outputs>

</Problem>"""

  geosInputFile.write(geosInputFileString)
  geosInputFile.close()


  # ===========================================
  #  Make a SLURM script to run GEOS.
  # ===========================================
  # This will run the job.
  # #SBATCH --export=NONE is needed because we are using mpi4py, which modifies
  # the environment, and that somehow gets passed through slurm and messes
  # up the srun command, causing it to hang unless we include this line.
  #
  # There was a failure was caused by PSM2 trying to use a kernel-assisted/CMA 
  # shared-memory transfer path that is broken or unavailable on that allocation, 
  # node, permission context, or runtime configuration.
  # It happened only in parallel, and was fixed by including
  #
  # export MV2_SMP_USE_CMA=0
  # export PSM2_KASSIST_MODE=none
  #
  # The cause is unknown.
  

  if flux:
    slurmScript = f"""#!/bin/bash

#flux: --job-name={jobName}
#flux: -N {mNodes:d} # number of nodes
#flux: -t {mWallTimeMinutes:d} # walltime in minutes
#flux: -B {mBank} # account
#flux: -q {mPartition} # queue to use
#flux: -l # Add task rank prefixes to each line of output.

export MPICH_GPU_SUPPORT_ENABLED=1
export HSA_XNACK=1

echo "Launching flux run command..."
export OMP_NUM_THREADS=1
flux run --env=* --exclusive -N{mNodes:d} -n{mCores:d} {geosPath} -i {geosInputFileName} -x {xpar:d} -y {ypar:d} -z {zpar:d} {restartStr}
echo "flux run command has completed, good bye."
"""
    fileName = timeStamp+"_runGEOS.sh"
    file = open(fileName, 'w')
    file.write(slurmScript)
    file.close()
  else:  
    slurmScript = f"""#!/bin/bash
#SBATCH -t {mWallTime}
#SBATCH -N {mNodes:d}
#SBATCH -n {mCores:d}
#SBATCH -A {mBank}
#SBATCH --export=NONE
#SBATCH -p {mPartition}

echo "Launching srun command..."
export OMP_NUM_THREADS=1
srun --export=ALL,MV2_SMP_USE_CMA=0,PSM2_KASSIST_MODE=none -n {mCores:d} {geosPath} -i {geosInputFileName} -x {xpar:d} -y {ypar:d} -z {zpar:d} {restartStr}
echo "srun command has completed, good bye."
"""

  fileName = f"{timeStamp}_runGEOS.sh"
  with open(fileName, 'w') as file:
      file.write(slurmScript)

  if mSubmitJobs:
      print(f'submitting job: {fileName} using Popen')
      if flux:
          output = subprocess.Popen(["flux", "batch", fileName], stdout=subprocess.PIPE).communicate()[0]
      else:
          output = subprocess.Popen(["sbatch", fileName], stdout=subprocess.PIPE).communicate()[0]

      output = str(output, 'UTF8').strip('Submitted batch job ')
      jobID = output.strip()
      print(f'Submitted job with ID = {jobID}')

  if mSubmitJobs and autoRestart:
      if flux:
          print('XXXX  autoRestart not supported with flux scheduler; not submitting a Slurm run-check job.')
      else:
          print('Auto restart enabled')
          print(f'run_check output = {output.strip()}')

          slurmScript = f"""#!/bin/bash
#SBATCH -t {runCheckTime}
#SBATCH -N 1
#SBATCH -p {mPartition}
#SBATCH -A {mBank}
#SBATCH --dependency=afterany:{jobID}

echo "launching pfw_check script..."
python3 pfw_check.py {inputFile} {jobID}
echo "pfw_check script has completed, good bye."
"""

          fileName = f"{timeStamp}_runCheck.sh"
          with open(fileName, 'w') as file:
              file.write(slurmScript)

          subprocess.call(["sbatch", fileName], cwd=PWD)
