/*
 * kernelMacros.hpp
 *
 *  Created on: Jul 17, 2019
 *      Author: settgast
 */

#ifndef CORECOMPONENTS_PHYSICSSOLVERS_SOLIDMECHANICS_KERNELMACROS_HPP_
#define CORECOMPONENTS_PHYSICSSOLVERS_SOLIDMECHANICS_KERNELMACROS_HPP_

#define UPDATE_STRESS 0



#endif /* CORECOMPONENTS_PHYSICSSOLVERS_SOLIDMECHANICS_KERNELMACROS_HPP_ */
