@startuml
<style>
classDiagram {
  class {
      ' attributes and methods
      FontColor blue
      ' class name
      header {
        FontSize 20
        FontStyle bold
      }
  }
}
</style>

set separator ::

!include Mesh.plantuml

!include Discretization.plantuml



Discretization::DiscretizationBase -- Mesh::MeshAbstract


Discretization::MeshInterface::NodeFieldManager -- Mesh::legacyGEOS::NodeManager
Discretization::MeshInterface::edgeFieldManager -- Mesh::legacyGEOS::edgeManager
Discretization::MeshInterface::FaceFieldManager -- Mesh::legacyGEOS::FaceManager

Discretization::MeshInterface::ElementManager -- Mesh::legacyGEOS::CellManager
Discretization::MeshInterface::ElementRegionBase -- Mesh::legacyGEOS::CellRegion
Discretization::MeshInterface::ElementSubRegionBase -- Mesh::legacyGEOS::CellSubRegion


@enduml