include(${CMAKE_CURRENT_LIST_DIR}/../../src/coreComponents/LvArray/host-configs/LLNL/dane-clang-14-mpm.cmake)

set( GEOS_ENABLE_CONTACT OFF CACHE BOOL "" FORCE)
set( GEOS_ENABLE_FLUIDFLOW OFF CACHE BOOL "" FORCE)
set( GEOS_ENABLE_INDUCEDSEISMICITY OFF CACHE BOOL "" FORCE)
set( GEOS_ENABLE_MULTIPHYSICS OFF CACHE BOOL "" FORCE)
set( GEOS_ENABLE_SIMPLEPDE OFF CACHE BOOL "" FORCE)
set( GEOS_ENABLE_SOLIDMECHANICS ON CACHE BOOL "" FORCE)
set( GEOS_ENABLE_SURFACEGENERATION OFF CACHE BOOL "" FORCE)
set( GEOS_ENABLE_WAVEPROPAGATION OFF CACHE BOOL "" FORCE)

# Fortran
set(CMAKE_Fortran_COMPILER /usr/tce/packages/gcc/gcc-12.1.1-magic/bin/gfortran CACHE PATH "")
set(CMAKE_Fortran_FLAGS_RELEASE "-O3 -g -DNDEBUG -march=native -mtune=native" CACHE STRING "")

# MPI
set(MPI_HOME /usr/tce/packages/mvapich2/mvapich2-2.3.6-clang-14.0.6-magic CACHE PATH "")

set(ENABLE_SPHINX OFF CACHE BOOL "")
set(ENABLE_YAPF OFF CACHE BOOL "")
set(ENABLE_PYGEOSX OFF CACHE BOOL "")
set(ENABLE_DOXYGEN OFF CACHE BOOL "")

include(${CMAKE_CURRENT_LIST_DIR}/dane-base.cmake)
