include(${CMAKE_CURRENT_LIST_DIR}/ruby-clang-14.cmake)

set( GEOS_ENABLE_CONTACT OFF CACHE BOOL "" FORCE)
set( GEOS_ENABLE_FLUIDFLOW OFF CACHE BOOL "" FORCE)
set( GEOS_ENABLE_INDUCEDSEISMICITY OFF CACHE BOOL "" FORCE)
set( GEOS_ENABLE_MULTIPHYSICS OFF CACHE BOOL "" FORCE)
set( GEOS_ENABLE_SIMPLEPDE OFF CACHE BOOL "" FORCE)
set( GEOS_ENABLE_SOLIDMECHANICS ON CACHE BOOL "" FORCE)
set( GEOS_ENABLE_SURFACEGENERATION OFF CACHE BOOL "" FORCE)
set( GEOS_ENABLE_WAVEPROPAGATION OFF CACHE BOOL "" FORCE)

# set(LVARRAY_BOUNDS_CHECK ON CACHE BOOL "" FORCE)