include(${CMAKE_CURRENT_LIST_DIR}/../../src/coreComponents/LvArray/host-configs/LLNL/ruby-gcc-12.cmake)

# MPI
set(MPI_HOME /usr/tce/packages/mvapich2/mvapich2-2.3.7-gcc-12.1.1-magic CACHE PATH "")

# ATS
set(ATS_ARGUMENTS "--machine slurm56"  CACHE STRING "")


set( GEOS_ENABLE_CONTACT OFF CACHE BOOL "" FORCE )
set( GEOS_ENABLE_FLUIDFLOW OFF CACHE BOOL "" FORCE )
set( GEOS_ENABLE_INDUCEDSEISMICITY OFF CACHE BOOL "" FORCE )
set( GEOS_ENABLE_MULTIPHYSICS OFF CACHE BOOL "" FORCE )
set( GEOS_ENABLE_SIMPLEPDE OFF CACHE BOOL "" FORCE )
set( GEOS_ENABLE_SOLIDMECHANICS ON CACHE BOOL "" FORCE )
set( GEOS_ENABLE_SURFACEGENERATION OFF CACHE BOOL "" FORCE )
set( GEOS_ENABLE_WAVEPROPAGATION OFF CACHE BOOL "" FORCE )

include(${CMAKE_CURRENT_LIST_DIR}/llnl-cpu-base.cmake)
