#!/bin/bash
#SBATCH -N 2048
#SBATCH -n 16384
#SBATCH -t 4:00:00
#SBATCH -J geos
#SBATCH -o frontier-%j-compflow-geom06.out

echo `date`
module load cpe/23.12
module load craype-accel-amd-gfx90a
module load rocm/5.4.3
export MPICH_GPU_SUPPORT_ENABLED=1
ldd ${1}
cmd="srun -N 2048 -n 16384 -c 1 --gpus-per-node=8 --ntasks-per-gpu=1 --gpu-bind=closest ${1} -i ECP_Wellbore_gpu.xml -x 16 -y 16 -z 64 ${2}"
echo "${cmd}"
${cmd}
echo `date`
echo 'Done'
