# MPM Minimal-TPL profile.
# Include this after a machine/compiler host-config.

set( GEOS_ENABLE_MPM_MINIMAL_TPL ON CACHE BOOL "" FORCE )
set( GEOS_ENABLE_LINEARALGEBRA OFF CACHE BOOL "" FORCE )
set( GEOS_LA_INTERFACE "None" CACHE STRING "" FORCE )
set( GEOS_ENABLE_CONSTITUTIVE_DRIVERS OFF CACHE BOOL "" FORCE )
set( GEOS_ENABLE_DENSE_LINEARALGEBRA OFF CACHE BOOL "" FORCE )
set( GEOS_ENABLE_CONSTITUTIVE_MPM_ONLY ON CACHE BOOL "" FORCE )

set( GEOS_ENABLE_TESTS OFF CACHE BOOL "" FORCE )
set( GEOS_INSTALL_SCHEMA OFF CACHE BOOL "" FORCE )

set( GEOS_ENABLE_CONTACT OFF CACHE BOOL "" FORCE )
set( GEOS_ENABLE_FLUIDFLOW OFF CACHE BOOL "" FORCE )
set( GEOS_ENABLE_INDUCEDSEISMICITY OFF CACHE BOOL "" FORCE )
set( GEOS_ENABLE_MULTIPHYSICS OFF CACHE BOOL "" FORCE )
set( GEOS_ENABLE_SIMPLEPDE OFF CACHE BOOL "" FORCE )
set( GEOS_ENABLE_SOLIDMECHANICS ON CACHE BOOL "" FORCE )
set( GEOS_ENABLE_SOLIDMECHANICS_MPM ON CACHE BOOL "" FORCE )
set( GEOS_ENABLE_SOLIDMECHANICS_FEM OFF CACHE BOOL "" FORCE )
set( GEOS_ENABLE_SURFACEGENERATION OFF CACHE BOOL "" FORCE )
set( GEOS_ENABLE_WAVEPROPAGATION OFF CACHE BOOL "" FORCE )

set( ENABLE_CALIPER OFF CACHE BOOL "" FORCE )
set( ENABLE_ADIAK OFF CACHE BOOL "" FORCE )
set( ENABLE_MATHPRESSO OFF CACHE BOOL "" FORCE )
set( ENABLE_PVTPackage OFF CACHE BOOL "" FORCE )
set( ENABLE_HPCREACT OFF CACHE BOOL "" FORCE )
set( ENABLE_METIS OFF CACHE BOOL "" FORCE )
set( ENABLE_PARMETIS OFF CACHE BOOL "" FORCE )
set( ENABLE_SCOTCH OFF CACHE BOOL "" FORCE )
set( ENABLE_SILO OFF CACHE BOOL "" FORCE )
set( ENABLE_VTK OFF CACHE BOOL "" FORCE )
set( ENABLE_SUPERLU_DIST OFF CACHE BOOL "" FORCE )
set( ENABLE_TRILINOS OFF CACHE BOOL "" FORCE )
set( ENABLE_HYPRE OFF CACHE BOOL "" FORCE )
set( ENABLE_PETSC OFF CACHE BOOL "" FORCE )
set( ENABLE_SUITESPARSE OFF CACHE BOOL "" FORCE )
set( ENABLE_PYGEOSX OFF CACHE BOOL "" FORCE )
set( ENABLE_DOCS OFF CACHE BOOL "" FORCE )
set( ENABLE_DOXYGEN OFF CACHE BOOL "" FORCE )
set( ENABLE_SPHINX OFF CACHE BOOL "" FORCE )
set( ENABLE_UNCRUSTIFY OFF CACHE BOOL "" FORCE )
set( ENABLE_XML_UPDATES OFF CACHE BOOL "" FORCE )

foreach( _tpl_dir
         ADIAK_DIR
         CALIPER_DIR
         MATHPRESSO_DIR
         METIS_DIR
         PARMETIS_DIR
         SCOTCH_DIR
         SILO_DIR
         SUPERLU_DIST_DIR
         SUITESPARSE_DIR
         TRILINOS_DIR
         HYPRE_DIR
         HYPREDRV_DIR
         PETSC_DIR
         VTK_DIR )
  unset( ${_tpl_dir} CACHE )
endforeach()
