import sys

#
# git log --since="2010-01-01" --until="2026-11-31" --all --pretty="%an" | sort | uniq | tr -d " ' " | xargs python3 repositoryStats_condenseDev.py
#

# Define the username mapping dictionary
username_mapping = {
"AleksNovikov":"aleksnovikov",
"AlexandreLapene":"alexandrelapene",
"AndreCosta":"andrecosta",
"AndreMacieiraBragaCosta":"andrecosta",
"AndreaBorio":"andreaborio",
"AndreaFranceschini":"andreafranceschini",
"AntoineMazuyer":"antoinemazuyer",
"AntoineMazuyer":"antoinemazuyer",
"ArnaudDUDES":"arnauddudes",
"ArturoVargas":"arturovargas",
"Aurelien":"aurelien",
"BESSETJulien":"julienrenethomasbesset",
"Ben":"bencorbett",
"BenCorbett":"bencorbett",
"BenjaminCorbett":"bencorbett",
"BenjaminCurticeCorbett":"bencorbett",
"BenjaminT.Liu":"benjamintliu",
"BertrandThierry":"bertrandthierry",
"BrianHan":"brianhan",
"BrianManhHienHan":"brianhan",
"CameronCrook":"cameroncrook",
"CameronMikelCrook":"cameroncrook",
"Castelletto":"castelletto",
"Castelletto1":"castelletto",
"ChaoyiWang":"chaoyiwang",
"ChrisWhite":"chriswhite",
"ChristopherSherman":"christophersherman",
"DanielOsei-Kuffuor":"danieloseikuffuor",
"DicksonKachuma":"dicksonkachuma",
"FanFei":"frankfeifan",
"Fei":"frankfeifan",
"frankfeifan":"frankfeifan",
"FrancoisHamon":"francoishamon",
"GuotongRen":"guotongren",
"Guotong-Ren":"guotongren",
"Gaetan":"gaetanfuss",
"GaetanFuss":"gaetanfuss",
"HerveGross":"hervegross",
"HeweiTang":"heweitang",
"HuiWu":"huiwu",
"IbrahimIsraa":"ibrahimisraa",
"IsaacJu":"isaacju",
"IsaacJu-debug":"isaacju",
"JacquesFranc":"jacquesfranc",
"JaisreeIyer":"jaisreeiyer",
"JamesCorbett":"jamescorbett",
"JeannePellerin":"jeannepellerin",
"JianHUANG":"jianhuang",
"JianHuang":"jianhuang",
"JieMeng":"jiaminjiang",
"JixiangHuang":"jixianghuang",
"JoshuaWhite":"joshuawhite",
"Julien":"julienrenethomasbesset",
"JulienReneThomasBesset":"julienrenethomasbesset",
"KevinJ.Dugan":"kevinjdugan",
"LionelUntereiner":"lioneluntereiner",
"LucasVALARCHER":"lucasvalarcher",
"MadonnaYoder":"madonnayoder",
"MamadouN'diaye":"mamadoundiaye",
"MamadouNdiaye":"mamadoundiaye",
"MarkKhait":"markkhait",
"Matteo":"matteocusini",
"MatteoCusini":"matteocusini",
"Matthias":"matthiascremon",
"MatthiasCremon":"matthiascremon",
"MelReyCG":"melreycg",
"MichaelHomel":"michaelhomel",
"MiladBader":"miladbader",
"MohammadKarimi-Fard":"mohammadkarimifard",
"NicolaCastelletto":"castelletto",
"Ouassim":"ouassim",
"PavelTomin":"paveltomin",
"PengchengFu":"pengchengfu",
"PeterB.Robinson":"peterbrobinson",
"PhillipChacon":"phillipchacon",
"QuanBui":"quanbui",
"RandolphR.Settgast":"randolphrsettgast",
"RandolphSettgast":"randolphrsettgast",
"RandySettgast":"randolphrsettgast",
"Ron-Wang":"ronwang",
"RyanAronson":"ryanaronson",
"SergeyKlevtsov":"sergeyklevtsov",
"Shabnam":"shabnamjandaghisemnani",
"ShabnamJandaghiSemnani":"shabnamjandaghisemnani",
"SohailWaziri":"sohailwaziri",
"StefanPovolny":"stefanpovolny",
"StefanoFrambati":"stefanoframbati",
"Sy-TuanNguyen":"sytuannguyen",
"TaehoKim":"taehokim",
"TaoJin":"taojin",
"TerryLigocki":"terryligocki",
"TheLastBlockbender":"phillipchacon",
"ThomasGAZZOLA":"thomasgazzola",
"ThomasGazzola":"thomasgazzola",
"TomByer":"tombyer",
"ThomasJamesByer":"tombyer",
"TotoGaz":"thomasgazzola",
"UncrustifyRobot":"randolphrsettgast",
"VictorA.P.Magri":"victorapmagri",
"VictorA.PaludettoMagri":"victorapmagri",
"WilliamRTobin":"williamrtobin",
"WilliamTobin":"williamrtobin",
"WuHuiLLNL":"wuhuillnl",
"XavierLacoste":"xavierlacoste",
"YohannDudouit":"yohanndudouit",
"YueHao":"yuehao",
"acitrain":"aurelien",
"andrembcosta":"andrecosta",
"arng40":"arnauddudes",
"aure-lily":"aurelily",
"castelletto1":"castelletto",
"cmcrook5":"cameroncrook",
"david4utd":"david4utd",
"dependabot[bot]":"randolphrsettgast",
"dkachuma":"dicksonkachuma",
"fanfei":"frankfeifan",
"fei2":"frankfeifan",
"francoishamon":"francoishamon",
"geosadmn":"randolphrsettgast",
"hannah_mairs":"hannahmairs",
"j0405284":"stefanoframbati",
"jacques":"jacquesfranc",
"jacquesn7":"jacquesfranc",
"jafranc":"jacquesfranc",
"jay-a":"jay-a",
"jfranc":"jacquesfranc",
"jiamin.jiang":"jiaminjiang",
"jiemeng-total":"jiaminjiang",
"joshua-white":"joshuawhite",
"joshwhite":"joshuawhite",
"julia.camargo":"juliacamargo",
"juliatcamargo":"juliacamargo",
"kimtaeho07":"kimtaeho07",
"labesse40":"labesse40",
"matteofrigo5":"matteofrigo5",
"mazuyer":"antoinemazuyer",
"mfrigo":"matteofrigo5",
"mkhait":"markkhait",
"mndiaye24":"mamadoundiaye",
"paloma-martinez":"palomamartinez",
"paveltomin":"paveltomin",
"povolny1":"stefanpovolny",
"rasimHZ":"rasimhz",
"robinspb":"robinspb",
"rustem.zaydullin@totalenergies.com":"rustemzaydullin",
"sframba":"stefanoframbati",
"shabnamjs":"shabnamjandaghisemnani",
"sohailwaziri":"sohailwaziri",
"stenix":"stenix",
"sytuannguyen":"sytuannguyen",
"tbeltzun":"tbeltzun",
"tjb":"tombyer",
"tony":"tony",
"wrtobin":"williamrtobin",
"ŁukaszŁaniewski-Wołłk":"lukaszlaniewski-wollk"
}

def count_unique_users(usernames):
    # Substitute usernames using the username mapping dictionary
    substituted_usernames = [username_mapping.get(username.strip(), username.strip()) for username in usernames]

    # Count the number of unique usernames
    unique_usernames = set(substituted_usernames)
#    print ("unique_usernames:", sorted(unique_usernames))
    num_unique_users = len(unique_usernames)
    return num_unique_users

# Example usage:
if __name__ == "__main__":
    # Read usernames from command line arguments
    usernames = sys.argv[1:]
    #print ("usernames:", usernames)

    # Count unique users
    num_unique_users = count_unique_users(usernames)
    
    # Output the number of unique users
    print(num_unique_users)
