# hostconfig to build only the wave solver on pangea3
#
#
include( ${CMAKE_CURRENT_LIST_DIR}/pangea3-gcc8.4.1-openmpi-4.1.2.cmake )

set ( GEOS_ENABLE_CONTACT OFF CACHE BOOL "" FORCE )
set ( GEOS_ENABLE_FLUIDFLOW OFF CACHE BOOL "" FORCE )
set ( GEOS_ENABLE_INDUCEDSEISMICITY OFF CACHE BOOL "" FORCE )
set ( GEOS_ENABLE_MULTIPHYSICS OFF CACHE BOOL "" FORCE )
set ( GEOS_ENABLE_SIMPLEPDE OFF CACHE BOOL "" FORCE )
set ( GEOS_ENABLE_SOLIDMECHANICS OFF CACHE BOOL "" FORCE )
set ( GEOS_ENABLE_SURFACEGENERATION OFF CACHE BOOL "" FORCE )

