

class Group #text:00000060
class ExecutableGroup #text:00000060
class TaskBase #text:00000060
class FieldStatisticsBase #text:00000060
class ObjectManagerBase #text:00000060
class ElementSubRegionBase #text:00000060
class ElementSubRegionBase #text:00000060
class WellSolverBase #text:00000060
class PhysicsSolverBase #text:00000060

class FieldStatisticsBase< SOLVER_T > #text:00000060 {
  string m_solverName (user input : "solverName")
  string m_outputDir (user input : "outputDir")
  bool m_writeCSV (user input : "writeCSV")
}

Group <|-- ExecutableGroup
ExecutableGroup <|-- TaskBase
TaskBase <|-- FieldStatisticsBase

Group <|-- ObjectManagerBase
ObjectManagerBase <|-- ElementSubRegionBase
ElementSubRegionBase <|-- CellElementRegion

WellSolverBase <|-- CompositionalMultiphaseWell
WellSolverBase <|-- SinglePhaseWell
PhysicsSolverBase <|-- WellSolverBase
ExecutableGroup <|-- PhysicsSolverBase

class CompositionalMultiphaseStatistics {
  m_computeCFLNumbers (user input: "computeCFLNumbers")
  m_computeRegionStatistics (user input: "computeRegionStatistics")
  m_relpermThreshold (user input: "relpermThreshold")
  --
  void postInputInitialization() override
  void registerDataOnMesh( Group & meshBodies ) override

  void computeRegionStatistics( time, meshLevel, regionNames )
  void computeCFLNumbers( time, dt, domainPartition )
}
FieldStatisticsBase <|-- CompositionalMultiphaseStatistics : SOLVER_T = CompositionalMultiphaseBase


class RegionStatistics {
  <color:Green>real64 dataTime
  ----
  void computeRegionStatistics< STATS_TYPES... >()
}
RegionStatistics <..l.. CompositionalMultiphaseStatistics
CellElementRegion *--> RegionStatistics : "<color:Green>Generated Group\n<color:Green>regionStatistics" 

note right of RegionStatistics::dataTime
  Added to keep track if stats has
  been computed for the current time.
  To be aware that stats are computer
  after solver computation, "dataTime"
  must be //timeStep + dt// (taking 
  into account the //dt// of cuts).
end note


class PressureStatistics #text:Green {
  real64 averagePressure
  real64 minPressure
  real64 maxPressure
  real64 minDeltaPressure
  real64 maxDeltaPressure
}
RegionStatistics *--> PressureStatistics : "<color:Green>Lazily Generated Wrapper\n<color:Green>pressure"
PressureStatistics [PressureStatistics] --> RegionStatisticsType : "<color:Green>implements"

class TemperatureStatistics #text:Green {
  real64 averageTemperature
  real64 minTemperature
  real64 maxTemperature
}
RegionStatistics *--> TemperatureStatistics : "<color:Green>Lazily Generated Wrapper\n<color:Green>temperature"
TemperatureStatistics [TemperatureStatistics] --> RegionStatisticsType : "<color:Green>implements"

class PoreVolumeStatistics #text:Green {
  real64 totalPoreVolume
  real64 totalUncompactedPoreVolume
  array1d<real64> phasePoreVolume
}
RegionStatistics *--> PoreVolumeStatistics : "<color:Green>Lazily Generated Wrapper\n<color:Green>poreVolume"
PoreVolumeStatistics [PoreVolumeStatistics] --> RegionStatisticsType : "<color:Green>implements"

class MassStatistics #text:Green {
  array1d<real64> phaseMass
  array1d<real64> trappedPhaseMass
  array1d<real64> immobilePhaseMass
  array2d<real64> componentMass
}
RegionStatistics *--> MassStatistics : "<color:Green>Lazily Generated Wrapper\n<color:Green>mass"
MassStatistics [MassStatistics] --> RegionStatisticsType : "<color:Green>implements"

class CFLNumbers #text:Green {
  array1d<real64> phaseMass
  array1d<real64> trappedPhaseMass
  array1d<real64> immobilePhaseMass
  array2d<real64> componentMass
}
RegionStatistics *--> CFLNumbers : "<color:Green>Lazily Generated Wrapper\n<color:Green>cflNumbers"
CFLNumbers [CFLNumbers] --> RegionStatisticsType : "<color:Green>implements"

interface RegionStatisticsType < STATS_TYPE > #text:Green {
  void init()
  void setKernelViews( RegionStatisticsKernelViews< STATS_TYPE > & views )
  HOST_DEVICE void collectElementStats( RegionStatisticsKernelViews< STATS_TYPE > const & views )
  void kernelReduce()
  void mpiReduce()
}

class STATS_TYPE::KernelViews < STATS_TYPE > #text:Green {
  ( structure of views necessary for collectElementStats() )
}
RegionStatisticsType [STATS_TYPE] ..> STATS_TYPE::KernelViews