#!/bin/bash
#SBATCH -N 512
#SBATCH -n 4096
#SBATCH -t 0:30:00
#SBATCH -J geos
#SBATCH -o frontier-%j-mechanics-geom05.out

echo `date`
module load cpe/23.12
module load craype-accel-amd-gfx90a
module load rocm/5.4.3
export MPICH_GPU_SUPPORT_ENABLED=1
ldd ${1}
cmd="srun -N 512 -n 4096 -c 1 --gpus-per-node=8 --ntasks-per-gpu=1 --gpu-bind=closest ${1} -i ECP_Wellbore_gpu.xml -x 8 -y 8 -z 64 ${2}"
echo "${cmd}"
${cmd}
echo `date`
echo 'Done'
