set( ENABLE_MATHPRESSO OFF CACHE BOOL "" )

set( ENABLE_PAMELA ON CACHE BOOL "" )
set( ENABLE_PVTPackage ON CACHE BOOL "" )

set( ENABLE_PETSC OFF CACHE BOOL "" FORCE )

set( ENABLE_CALIPER OFF CACHE BOOL "" )
set( ENABLE_PAPI OFF CACHE BOOL "" )

set( ENABLE_ESSL OFF CACHE BOOL "" )

set( ENABLE_TRILINOS OFF CACHE BOOL "" )

set( CAMP_STANDALONE TRUE CACHE BOOL "" )

# ROCM options
set( ENABLE_ROCM ON CACHE BOOL "" FORCE )
set( ROCM_ROOT "${HIP_ROOT}" CACHE PATH "" )

set( GEOS_BUILD_OBJ_LIBS OFF CACHE BOOL "" FORCE )

set( ENABLE_GTEST_DEATH_TESTS OFF CACHE BOOL "" )
set( gtest_disable_pthreads ON CACHE BOOL "" )

set( GEOS_ENABLE_TESTS OFF CACHE BOOL "" FORCE )
set( ENABLE_EXAMPLES OFF CACHE BOOL "" FORCE )
set( ENABLE_BENCHMARKS OFF CACHE BOOL "" FORCE )
set( ENABLE_DOCS OFF CACHE BOOL "" FORCE )

set( ENABLE_SCOTCH OFF CACHE BOOL "" FORCE )
set( ENABLE_SUPERLU_DIST OFF CACHE BOOL "" FORCE )

set( GEOS_BUILD_OBJ_LIBS OFF CACHE BOOL "" FORCE )

set( CMAKE_CXX_STANDARD 17 CACHE STRING "" )
set( BLT_CXX_STD c++17 CACHE STRING "" )
