b0=$(basename $0)
d0=$(dirname $0)
if [ "$d0" == "." ]; then 
    f0=$b0
else
    f0=$0
fi 
# echo "### \$0=$0, \$d0=$d0, \$b0=$b0, \$f0=$f0"
if [[ $general_help == "1" ]] ; then 
    echo "## $f0 : clone, configure, build and install TPL and GEOS with different configurations."
    echo "#  "
    echo "#  Chevron CTC, Innovation and HPC R&D"
    echo "#  "
    echo "##          "
    echo "##         ' list ' is a 'space-separeted list of items', enclosed in single or double quotes"
    echo "##         [] : optional, { | } alternatives "
    echo "##          "
    echo "## Usage : [optional EnvVar=... See below] $0 { CONFIG_NAME | --help }"
    echo "##         HOST_CONFIG_DIR=${HOST_CONFIG_DIR} directory path prefix for Chevron's host-configs; can be changed "
    echo "##         CONFIG_NAME is this part of the path: ${HOST_CONFIG_DIR}/CONFIG_NAME.cmake"
    echo "##         Locations to clone, install and build GEOS and TPL"
    echo "##         [sroot=/full/dir/prefix/to/clone/GEOS]; default=$(pwd)" 
    echo "##         [iroot=/full/dir/prefix/to/install/GEOS]; default=$(pwd)" 
    echo "##         [croot=/fast/file/system/dir/prefix/to/build/TPL and GEOS]; default=/dev/shm/${USER}/src; do not modify in not sure of its function " 
 fi
    echo "##          "
    echo "## --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
    echo "##         [CLONE=${CLONE}] ; {0,1} : 0 : do not clone, 1 = clone"
    echo "##         [BUILD=${BUILD}] ; {0,1} : 0 : do not build, 1 = update and build"
    echo "##         [BUILD_TYPE=${BUILD_TYPE}] : Release, Debug or RelWithDebInfo ; build_type= ${build_type}  "
    echo "##         [TPL=${TPL}] ; {0,1} : 1 = perform TPL related tasks, 0 = skip TPL "
    echo "##         [gitTPL=${gitTPL}] : change this to point to another repo, such as Chevron's ADO"
    echo "##         [TPL_UPDATE=${TPL_UPDATE}] : 0 = do not update from Github repos; 1 = update" 
    echo "##         [TPL_RESET=${TPL_RESET}] : '--type { HEAD~n | hash }' to reset before building TPL targets'" 
    echo "##         [TPL_REBASE=${TPL_REBASE}] : 1 = 'git pull --rebase' " 
    echo "##         [TPL_BUILD_ONLY=\"${TPL_BUILD_ONLY}\"] {0|' list '} ; 0 = configure and build all TPL packages, 'list ' = only rebuild those in 'list'"
    echo "##         [TPL_CMAKE_VARS=\"${TPL_CMAKE_VARS}\"] : Additional variables for the TPL CMake configure command lines: -DVAR=val" 
    echo "##          "
    echo "##         [GEOS=${GEOS}] ; {0,1} : 1 = carry out GEOS related tasks, 0 = skip GEOS "
    echo "##         [gitGEOS=${gitGEOS}] : change this to point to another GEOS repo, such as Chevron's ADO"
    echo "##         [GEOS_MAIN_BRANCH=${GEOS_MAIN_BRANCH}] ; default GEOS branch_name  : checkout this GEOS branch before updating GEOS"
    echo "##         [GEOS_REBUILD=${GEOS_REBUILD} ] ; {0,1} : 1 rebuild GEOS without update and configure steps, 0 = update, configure and build all GEOS targets"
    echo "##         [GEOS_UPDATE=${GEOS_UPDATE}] : 0 = do not update from Github repos; 1 = update" 
    echo "##         [GEOS_RESET=${GEOS_RESET}] : '--type { HEAD~n | hash }' to reset before building GEOS targets'" 
    echo "##         [GEOS_REBASE=${GEOS_REBASE}] : 0 = apply Git merge, 1 = apply Git merge with '--rebase' option" 
    echo "##                                      : 1 = 'git pull --rebase' " 
    echo "##         [GEOS_BUILD_ONLY=\"${GEOS_BUILD_ONLY}\"] : {0|' list '}] : 0 = configure and build all targets, 'list ' = only build those in 'list'"
    echo "##         [GEOS_CMAKE_VARS=\"${GEOS_CMAKE_VARS}\"] : Additional variables for the GEOS Cmake configure command lines: -DVAR=val" 
    echo "##         [GEOS_HOST_FLAGS_CLI=\"${GEOS_HOST_FLAGS_CLI}\"] : Additional options for the host compilation command line, e.g., -DVAR=val" 
    echo "##         [GEOS_CUDA_FLAGS_CLI=\"${GEOS_CUDA_FLAGS_CLI}\"] : Additional options for the CUDA compilation command line, e.g., -DVAR=val" 
    echo "##         [TPL_BRANCH=${TPL_BRANCH}] ; branch_name : checkout this TPL branch before building TPL"
    echo "##         [GEOS_BRANCH=${GEOS_BRANCH}] ; branch_name  : checkout this GEOS branch before building GEOS"
    echo "##         [GEOS_INSTALL=$GEOS_INSTALL}] ; {0,1} : 1 = install GEOS targets after build, 0 = do not install"
    echo "##         [GEOS_PYTHON_TOOLS=${GEOS_PYTHON_TOOLS}] ; {0,1} : 0 = do not build Pyton/XML environment and tools, 1 = build  "
    echo "##         [GEOS_INTEGRATED_TESTS=${GEOS_INTEGRATED_TESTS}] ; {0,1}] : 0 = do not build ATS environment and tools, 1 = build  "
    echo "##         [ENABLE_CALIPER_HYPRE={OFF,ON}] : OFF = do not build Hypre with Caliper instrumentation, ON = build with "
    env | egrep 'ENABLE(.*)=' | sort | gawk '{print "##         ", $0 }'
    echo "##         [LCACHE=${LCACHE}] ; {0,1,2,3,4} : 0 = do not use local cache, 1 = use, 2 = clear cache, 3 = copy GEOS build back to $sroot. 4 = copy everything back to $sroot "
    echo "##          "
    echo "##         Compiler tool-chains and MPI stacks "
    echo "##         [comp=${comp}]  : set comp to point to 'environment modulefile(s)' of the desired compiler version"
    echo "##         [gpu_comp=${gpu_comp}]  : set gpu_comp to point to 'environment modulefile(s)' of the desired CUDA compiler version"
    echo "##         [mpi=${mpi}]  : set mpi to point to 'environment modulefile(s)' of the desired MPI version"
    echo "##         [modules=\"${modules}\"]  : set modules to point to 'list of modulefiles to also load"
    echo "##         [CTEST=${CTEST}] ; {0,1} : 1 = run all quality unit tests on GEOS after installation"
    echo "##          "
    echo "##         [V=${V}] : 0 = minima1, 1 = some, 2 = more verbosity "
    echo "##         [MODULES=\"${MODULES}\"]  : final set of modulefiles to load before compiling TPL and GEOS; also loaded before running GEOS"
    echo "##          "
    echo "## --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
    echo "##          "

 
if [[ $general_help == "1" ]] ; then 
    echo "## Quick Instructions for BASH shell. Or type '/bin/bash' first to jump to BASH"
    echo "   export SCR=/where/you/cloned/SubSurf-DIGITAL-GEOSX-scripts "
    echo "   export sroot=/where/you/want/GEOS/cloned/and/built "
    echo "   export iroot=/where/you/want/GEOS/installed "
    echo "## --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
    echo ""
    echo "## Note: we may now do both CLONE=1 BUILD=1 on the same command"
    echo ""
    echo "#  1. First, clone both TPL and GEOS in a clean directory (first time)"
    echo "   { CLONE=1 | BUILD=0 } TPL=1 GEOS=1 \${SCR}/$f0 CONFIG_NAME "
    echo "#  2. To update + configure + build and install both TPL and GEOS afterwards:  "
    echo "   BUILD=1 TPL=1 GEOS=1 \${SCR}/$f0 CONFIG_NAME "
    echo "#  3. To update + configure + build and install only GEOS afterwards. No need to rebuild TPL unless it has been modified:  "
    echo "   BUILD=1 GEOS=1 \${SCR}/$f0 CONFIG_NAME "
    echo "#  4. To update + configure + build and install only GEOS afterwards and use a compatible (where CONFIG_NAME does not match) TPL already installed:  "
    echo "   GEOSX_TPL_DIR='/where/TPL/is/already/installed' BUILD=1 GEOS=1 \${SCR}/$f0 CONFIG_NAME "
    echo "#  5. To update + re-build and install only specific TPL packages in 'list' :  "
    echo "   BUILD=1 TPL=1 TPL_BUILD_ONLY=' X Y Z  ' \${SCR}/$f0 CONFIG_NAME "
    echo "#  6. To update + re-build and install only specific GEOS packages in 'list' or just geosx :  "
    echo "   BUILD=1 GEOS=1 GEOS_BUILD_ONLY={ 1 | geosx } \${SCR}/$f0 CONFIG_NAME "
    echo "#  7. To only re-build and install geosx binary without updating or re-configuring:  "
    echo "   BUILD=1 GEOS=1 GEOS_REBUILD=1 \${SCR}/$f0 CONFIG_NAME "
    echo "#  8. To only re-build but not re-configure after local modifications in GEOS :  "
    echo "   BUILD=1 GEOS=1 GEOS_REBUILD=1 GEOS_BUILD_ONLY=1 \${SCR}/$f0 CONFIG_NAME "    
    echo "#  9. To configure + build + install TPL and GEOS at a particular GEOS BRANCH or Github commit point: "
    echo "   GEOS_BRANCH='CVX/residual-flash' V=1 BUILD_ONLY=1 TPL=1 GEOS=1 \${SCR}/$f0 CONFIG_NAME "
    echo "#  10. To configure + build + install TPL and GEOS at a particular TPL and GEOS BRANCH or Github commit points: "
    echo "   TPL_BRANCH='hypre-update' BRANCH_GEOS='CVX/residual-flash' V=1 BUILD_ONLY=1 TPL=1 GEOS=1 \${SCR}/$f0 CONFIG_NAME "
    echo "#  11. To configure + build GEOS in \$sroot without fast local caching and **not install GEOS** (at the install-XXX location) :  "
    echo "   BUILD=1 LCACHE=0 GEOS=1 GEOS_INSTALL=0 \${SCR}/$f0 CONFIG_NAME "
    echo "#  12. To configure + build TPL and GEOS in \$sroot with Integrated Tests support, build GEOS without fast local caching and not install GEOS at \$iroot :  "
    echo "   BUILD=1 LCACHE=0 TPL=1 GEOS=1 GEOS_INTEGRATED_TESTS=1 GEOS_INSTALL=0 \${SCR}/$f0 CONFIG_NAME "
    echo "#  13. To configure + build TPL in \$iroot fast with local caching and then build GEOS with Integrated Tests (ATS) in \$sroot/GEOS/GEOS/build-XXX:  "
    echo "   BUILD=1 LCACHE=1 TPL=1 GEOS=0 \${SCR}/$f0 CONFIG_NAME "
    echo "   BUILD=1 LCACHE=0 TPL=0 GEOS=1 GEOS_INTEGRATED_TESTS=1 GEOS_INSTALL=0  \${SCR}/$f0 CONFIG_NAME "
    echo "#  14. To configure + build in \$sroot with Integrated Tests (ATS) (after matching TPL already installed) select no fast local caching (can use GEOS and ATS in \$sroot/GEOS/GEOS/build-XXX:  "
    echo "   BUILD=1 LCACHE=0 GEOS=1 GEOS_INTEGRATED_TESTS=1 GEOS_INSTALL=0 \${SCR}/$f0 CONFIG_NAME "
    echo "#  15. To configure + build + install and run all unit tests afterwards:   "
    echo "   BUILD=1 TPL=1 GEOS=1 CTEST=1 \${SCR}/$f0 CONFIG_NAME "
fi
    echo "##          "

