name: Pull Request

on:
  pull_request:
  workflow_dispatch:

# Cancels in-progress workflows for a PR when updated
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
    
jobs:
  run_compliance_checks:
    name: Compliance Checks
    uses: ./.github/workflows/compliance.yml
    secrets: inherit

  run_builds:
    # if: opened, synchronize, or reopened, ready_for_review
    needs:
      - run_compliance_checks
    name: Build step
    uses: ./.github/workflows/builds.yml
    with:
        DOCKER_IMAGE_TAG: ${{ needs.run_compliance_checks.outputs.DOCKER_IMAGE_TAG }}
    secrets: inherit